### ISSUE TITLE
[PUBLICAÇÕES] Formulário DOIFD

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#100]
O funcionamento atual do formulário das publicações dispõe do disparo do email com o arquivo de download através da utilização do plugin DOIFD.

- [ ] Migrar os dados dos downloads novamente para atualizar a lista de contatos, quantidade de downloads e arquivos
- [x] Exibir arquivos de download na página de upload do WP

**Comment by jacsonp** [comment]
no ambiente onde tem os arquivos de mídia está funcionando, o dev não tem fisicamente os arquivos

**Comment by jacsonp** [comment]
Resolvido ao migrar tabelas:
{prefix}doifd_lab_downloads
{prefix}doifd_lab_forms
{prefix}doifd_lab_subscribers
