### ISSUE TITLE
[CABEÇALHO] Desconfigura em versões antigas do firefox

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#102]
Na versão 124 e anteriores o cabeçalho fica com o layout desconfigurado:

![Image](https://github.com/user-attachments/assets/d0e149b3-1aaf-4d89-9e35-af249bc24947)

**Comment by dioliviers** [comment]
Site já carregando corretamente testado nas versões : 128(última), 127 e 126;

**Comment by daphnemartinsba** [comment]
Menu na versão 128 do firefox:


![Image](https://github.com/user-attachments/assets/4a385e57-2039-4735-9c76-31984d502360)
