### ISSUE TITLE
[ACESSIBILIDADE] Inserir ícones no menu do topo

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#106]
- [ ] Inserir ícones do vlibra e user way no menu do topo (ícones substituirão os ícones anteriores de acessibilidade)

Menu onde ícone deve ser inserido: 

![Image](https://github.com/user-attachments/assets/2f7e5544-67c9-47b3-bb9b-1ec38ea741af)

**Comment by dioliviers** [comment]
Foi feito o alinhamento com a @marinarcruz de ajustar o posicionamento dos icones flutuantes, chegamos a conclusão de que mantendo ele na mesma posição porém ajustar horizontalmente a distancia entre eles teriamos uma solução.

Eu ajustei o de acessibilidade ele estava muito em cima do header e do v-libras eu subi o icone ( não muito ), porque se ele ficasse aninhado com o de acessibilidade dificultaria na abertura do modal para a exibição do assistente, da mesma forma que implicaria na abertura do modal do v-libras no subheader ( lado esquerdo dos icones de redes sociais ) , queria saber a opinião de vocês sobre oque foi feito.
https://ethos.hacklab.com.br/

**Comment by daphnemartinsba** [comment]
Validado pelo cliente
