### ISSUE TITLE
[INTEGRAÇÃO CRM] NOSSAS ASSOCIADAS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#108]
https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=353-3889&t=DWWdXkrvOtN25amM-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2

- Está com shortcode 
- [x] Estilizar CSS (não dá para mexer no html), deixar mais próximo possível do figma  @barbaburns 
- [x] baixar logos no CRM e deixar na pasta onde estão as imagens dos associados

**Comment by marinarcruz** [comment]
Integrar as logos diretamente com o CRM

**Comment by marinarcruz** [comment]
05/08: combinamos com o cliente que eles verificarão onde estão localizadas essas logos no CRM. (Nicholas)

**Comment by marinarcruz** [comment]
06/08: faremos por shortcode.
