### ISSUE TITLE
[ARCHIVE POSTS] Criar página de arquivo para os termos dos CPTs POST, INICIATIVAS, EVENTOS, PUBLICAÇÕES

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#11]
Links das archives em construção: 

https://ethos.hacklab.com.br/iniciativa/
https://ethos.hacklab.com.br/publicacao/
https://ethos.hacklab.com.br/tipo-post/posicionamento-institucional/
https://ethos.hacklab.com.br/tipo-post/opinioes-e-analises/
https://ethos.hacklab.com.br/tipo-post/novidades/
https://ethos.hacklab.com.br/agenda/
https://ethos.hacklab.com.br/agenda/categoria/cursos/
https://ethos.hacklab.com.br/agenda/categoria/grupos-de-trabalhos/

======**======

Obs: como as archive tem o mesmo estilo, criamos uma única issue para que o CSS seja aplicar de forma igual para todas as archives.

- [x] Criar página archive para as CPTs: POST, INICIATIVA, EVENTO, PUBLICAÇÃO
- [x] Criar cpt de cabeçalhos e rodapé para archives.

Archives dos termos:
- [x] Criar cabeçalho para a archive do termo **Posicionamentos institucionais**  (CPT POST)

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=202-772&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=202-772&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive do termo **Novidades** (CPT POST) 

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=220-1888&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18821&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive do termo **Opinião** (CPT POST)

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1666-74322&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18872&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive **INICIATIVAS** (CPT INICIATIVAS)

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=231-2043&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19015&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive do termo **Cursos** (CPT EVENTO)

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=685-13375&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19101&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive do termo **Grupos de Trabalho** (CPT EVENTO)

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=329-2415&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19229&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive  **Publicações** (CPT PUBLICACAO)

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=329-2645&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19283&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

- [x] Criar cabeçalho para a archive dos demais termos do CPT EVENTO.

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=361-3596&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1500-11243&t=wHpGRcirZ3fWYHk4-0&scaling=min-zoom&page-id=112%3A2

**Comment by daphnemartinsba** [comment]
O layout das archives de eventos, cursos e grupo de trabalhos será a página de AGENDA (Lista/calendário)

**Comment by daphnemartinsba** [comment]
Cabeçalho das archives de Grupo de Trabalho e Cursos será estilizado na issue #47

**Comment by caio-ascava** [comment]
- [ ] - o metadado de Todas as Áreas está em inglês... os demais estão ok
- [ ] - pequena alteração entre a ordem das abas (conforme Figma é "Todas as Áreas/direitos humanos/integridade/meio ambiente/institucional").. .dev (all the areas/Direitos humanos/institucional/Integridade/Meio Ambiente).. Ou seja, precisa colocar "Institucional" no final que já resolve)
- [ ] - as tags que estão diferentes do layout.. mas o Thiago comentou que será necessário rever tamanho das tags e quantidade de tags por card para evitar a quebra de layout..
- [ ] - a cor e tamanho das setas (< / >) ao mudar de página
- [ ] - as archives que possuem data de publicação abaixo do títulos de cada thumb são a de novidades(dev ta sem data), de publicações (dev está em inglês, precisa traduzir), posicionamentos institucionais (dev está sem data)

**Comment by thiagolamonte** [comment]
comentário: no layout a archive de novidades não possui data no card



![Image](https://github.com/Ethos-ti/SiteEthos/assets/53320806/c676a64e-53bb-45b2-8208-b500d5ce4e79)

**Comment by daphnemartinsba** [comment]
- Paginação com bug está sendo investigada

**Comment by daphnemartinsba** [comment]
Bug nas páginas da ARCHIVE DE PUBLICAÇÕES será resolvida na issue #66
