### ISSUE TITLE
[HOME] Debugar BLOCO DE AGENDA no novo.ethos

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#118]
Atualmente, o bloco de agenda não aparece mais na home, precisa debugar para entender o porquê não aparece e solucionar para que apareça novamente
https://novo.ethos.org.br/

**Comment by marinarcruz** [comment]
Bloqueada pela issue 125

**Comment by marinarcruz** [comment]
deletar os eventos do novo.ethos que forem de teste, pelo plugin, no painel
