### ISSUE TITLE
[CONTATO]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#12]
- [x] Utilizar contact form 7 - quando for fazer esse, chamar a MariSol pois ela precisa documentar
- [x] Aplicar widget de parcerias/apoio  
- [ ] Utilizar elementos do inventário de componentes para avisos/alertar de campo sem preenchimento 
- [ ] Modal de confirmação de envio :

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/6ed4228f-828f-4553-a438-2a6cae685047)

- texto deve ser: Em breve a equipe do Instituto Ethos entrará em contato!

- disparo de email necessita de configuração do mailgun #4 

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18796&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=208-13&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2

Inventário de componentes: https://www.figma.com/file/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=578-5887&mode=design&t=4VXQQQ6WQ8tiCTWj-0

**Comment by dioliviers** [comment]
falta fazer o modal de confirmação, porém amanhã na semanal vou tentar alinhar para verificar a necessidade do modal que está descrito na issue mas não tem modal de envio no layout do contato, minha sugestão é mantermos as 'warnnings e confirmação de envio padrão' do contact form. Visto que é um plugin e alterar estilização de plugin, se houver algum tipo de atualização ou alteração nas classes padrão do plugin, há o risco de perder toda estilização.

**Comment by dioliviers** [comment]
Conforme informado na semanal, vamos seguir os alertas e confirmação de envio padrão do contact-form.
Os espaços entre os inputs é natural do plugin porque dentre esses espaços ele reserva a warnning caso o campo não seja preenchido

-> incluso já o aceite dos termos
-> tag do [recaptcha] foi inclusa, porém não aparece ainda porque tem que instalar o plugin e cadastrar uma key
