### ISSUE TITLE
[LOGIN/RECUPERAÇÃO DE SENHA] ATUALIZAR PMPRO e CORRIGIR CSS & JS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#123]
- [x] Atualizar pmpro no local
- [x] corrigir o CSS e JS conforme layouts

Layout login: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=4983-33418&t=Ro5Sczv9xUNBG8h2-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2
Layout recuperação de senha: 

![Image](https://github.com/user-attachments/assets/bcdfdce8-a62a-436f-97d6-34bea525fc55)

URL login: https://novo.ethos.org.br/login/
URL recuperação de senha: https://novo.ethos.org.br/login/?action=reset_pass

**Comment by daphnemartinsba** [comment]
### Login
Layout ANTES da atualização do pmpro:
![Image](https://github.com/user-attachments/assets/33feaece-640e-4417-b717-2391d8ad1aaa)


- [ ] Traduzir ou ocultar show password
- [ ] posicionar esqueci a senha logo abaixo do campo de senha
- [ ] Afastar título Login do header (se basear no layout antes da atualização do pmpro)

![Image](https://github.com/user-attachments/assets/0ad28d8a-142a-411e-953d-c6ea8794d70b)

- [ ] Diminuir distância entre botão entrar e o texto abaixo do botão (se basear no layout antes da atualização do pmpro)

![Image](https://github.com/user-attachments/assets/cf7be241-af3a-4c3c-9329-69bd7e23b72a)


### Recuperação de senha

**Comment by dioliviers** [comment]
Obs: faltou fazer a tradução, a única vez que tentei fazer infelizmente deu problema e outro colega fez pra mim rs. Vou pedir um help e já traduzimos show password e hide password.

**Comment by daphnemartinsba** [comment]
- [ ] Mobile iphone pro:


![Image](https://github.com/user-attachments/assets/3012f591-b606-4409-bfb9-77641cf33a59)

- [ ] Traduzir string "Show password"

**Comment by filipesouzadev** [comment]
Optei por ocultar a string como sugerido no primeiro checkbox por conta do meu Poedit que não encontra as strings traduzidas o que dificulta uma nova tradução.

sobre o erro do browserstack, emulei novamente e obtive o erro, mas testando no meu aparelho iphone 13 e em outro aparelho, iphone 15 pro, não consegui reproduzir a quebra.



![Image](https://github.com/user-attachments/assets/e84b62a3-397c-474a-9490-306907511ae2)
![Image](https://github.com/user-attachments/assets/b30c66a0-7267-4d9b-8ef9-72960607cd5b)
