### ISSUE TITLE
[ÁREA DE ASSOCIADOS] PLANILHA DE PRIMEIRO ACESSO DE ASSOCIADAS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#126]
Extrair planilha com links para primeiro acesso das empresas que já são associadas e tiveram seus cadastros importados para o WP
Inserir na extração os dados do ID da Conta

A planilha deve conter os seguintes campos:

- ID do cliente
- ID do usuário
- Nome do usuário
- Login do usuário
- E-mail do usuário
- ID da conta
- Nome da conta

**Comment by marinarcruz** [comment]
06/08: voltou: precisa checar e reenviar

**Comment by daphnemartinsba** [comment]
planilha enviada no dia 07/08
