### ISSUE TITLE
[INTEGRAÇÃO CRM] ATUALIZAÇÕES DE PERMISSÕES e ADIÇÃO DE CONTATOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#127]
- [x] Atualizar contato primário do CRM para o WP
- [x] WP deve possuir no máximo 3 admins, contato primário, contato alternativo 1 e contato alternativo 2 do CRM
- [x] Ao adicionar um contato no WP deve adicionar um contato na conta no CRM
- [x] Ao adicionar um contatno na conta no CRM deve criar um cadastro no WP:
  - Avaliar como esse contato terá acesso a senha da conta

**Comment by leopiccionia** [comment]
- [ ] Criação de contato
- [x] Criação de lead
- [x] Alteração de aprovador
    - [ ] Impedir contas sem aprovador 
- [x] Adição e remoção de administrador
    - [ ] Remoção do contato principal 
- [x] Edição de conta
- [ ] Edição de lead
- [ ] Edição de contato
