### ISSUE TITLE
[SINGLE POST] 

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#13]
- [x] criação do componente `_single.scss`
- [x] refactory do `single.php`

obs: seção PARCERIAS será um componente a parte.

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=280-1950&t=IjdMwILX9JglG5lB-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-18924&t=IjdMwILX9JglG5lB-0&scaling=min-zoom&page-id=112%3A2

**Comment by filipesouzadev** [comment]
@daphnemartinsba referenciando aqui que o refactory foi feito no tema-base e será aplicado aqui com merge.

**Comment by filipesouzadev** [comment]
link para validação https://ethos.hacklab.com.br/instituto-ethos-celebra-25-anos-em-evento-em-sao-paulo-com-debate-sobre-as-desigualdades-2/

**Comment by estercmandrade** [comment]
- [ ] investigar a bug nas singles de páginas e posts

**Comment by daphnemartinsba** [comment]
- [ ] Fazer bloco Leia também

**Comment by daphnemartinsba** [comment]
A label revisão foi utilizada em primeiro momento por conta de um bug que não foi decorrente dessa issue, era um bug no ambiente de modo geral

**Comment by caio-ascava** [comment]
**Desktop**

- [ ] 1- Incluir a legenda da foto (em dev, imagem por e texto por estão ao final da página)
- [ ] 2- A imagem destaque tem 1167x656 de tamanho no Figma
- [ ] 3- Aumentar distanciamento entre o texto abaixo do titulo e data da publicação.
- [ ] 4- No Figma a imagem principal (nao a de destaque) possui "titulo da galeria" no canto superior esquerdo e legenda no rodapé dentro da imagem.
- [ ] 5- No bloco "LEIA TAMBEM" ajustar a ordem das etiquetas de editorias/temas ( categoria / tema )
- [ ] 6- As thumbs devem possuir resolução de 370x208 com distanciamento entre elas de 31px
- [ ] 7- As tags inseridas abaixo das thumbs ajustar a fonte (font-family: Montserrat);

font-size: 12px;
font-weight: 700;
line-height: 14.63px;
text-align: left;, 

- [ ] 7- Ajustar layout da etiqueta (retangular com letras em caixa alta) e distanciamento da thumb acima.
- [ ] 8- Tradução de data da publicação e autor.
- [ ] 9- Ajustar os ícones de redes sociais para compartilhamento que estão com design diferente entre Figma e dev.
- [ ] 10- Alterar fonte do texto de Opens Sans-serif para Inter Sans-serif
- [ ] 11- Títulos de "PARCERIA INSTITUCIONAL", 'PARCERIA ESTRATEGICA" E "APOIO INSTITUCIONAL" no figma estão em negrito com fonte Inter sans-serif 400 e cor #000000e5

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/de324459-46aa-4f65-a591-f4fe649887ab)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/c410a1c3-8e52-43e1-a75d-9451e8716b77)

**Comment by caio-ascava** [comment]
Metadado do "Leia também" está sem categoria, no entanto, deveria puxar o termo do CPT. Se está em noticias, deveria trazer a tag NOTICIAS

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/80a18879-61e4-4577-9752-87bf47437e88)

**Comment by filipesouzadev** [comment]
@caio-ascava o item:

`4- No Figma a imagem principal (nao a de destaque) possui "titulo da galeria" no canto superior esquerdo e legenda no rodapé dentro da imagem.`

na verdade não é uma imagem de destaque, é um bloco de galeria de imagens do hacklab blocks. neste momento não estamos utilizando.

sobre o item:
`8- Tradução de data da publicação e autor.`

acredito que estamos tratando em outras issues, visto que, todas as strings do projeto precisarão de tradução.

sobre o item:
`7- Ajustar layout da etiqueta (retangular com letras em caixa alta) e distanciamento da thumb acima.`

conversei com o Pedro pelo canal do rocket e o padrão de todas as tags é o com bordas arredondadas, pode desconsiderar o que está com com retangular no layout.

sobre as imagens, conforme falamos na weekly seguimos um padrão do aspect ratio, não colocamos medidas fixas para não desconfigurar  a imagem.
