### ISSUE TITLE
[DADOS DA EMPRESA] Edição dos campos

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#131]
Alterar os campos editáveis na tela de Perfil da Empresa, aba Dados da Empresa (não editáveis: CNPJ, Razão Social, CNAE, Faturamento do ano anterior; Inscrição Municipal, Inscrição Estadual, Porte, Quantidade de Empregados). 

- [x] Retirar campo: Logomarca da empresa

- [x] Campos que devem ser editáveis: Nome fantasia, setor/segmento,  website, todos os campos de endereço

**Comment by thiagolamonte** [comment]
parte estrutural solicitada na tarefa ok

**Comment by marinarcruz** [comment]
06/08: Thiago fez, mas ainda estamos finalizando a integração com o CRM. Leo
