### ISSUE TITLE
[INTEGRAÇÃO CRM] DADOS DOS EVENTOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#133]
- [x] Ao criar um evento no CRM o corpo do texto e os metadados devem ser puxados para o WP

- Título
- Categoria
- Início
- Fim
- Investimento/ preço do evento
- Local
- Website do evento
- Conteúdo de texto

A relação desses campos no WP e no CRM então aqui:
https://docs.google.com/spreadsheets/d/1d03Uhei3213LirGkN5bOFmrzyxh_9bc09Po6gtukFA8/edit?usp=sharing 

- [x] Ao atualizar os dados do evento no CRM, devem ser atualizados no WP

- [ ] Investigar se o campo para link da inscrição criado no pods será utilizado e caso não, retirá-lo 

- [x] Solucionar warnings: 
Warning: Undefined property: stdClass::$fut_dt_data_encerramento_inscricoes in /home/site/wwwroot/wp-content/themes/hacklab-theme/single-evento.php on line 92

Warning: Undefined property: stdClass::$fut_dt_data_encerramento_inscricoes in /home/site/wwwroot/wp-content/themes/hacklab-theme/single-evento.php on line 96

**Comment by leopiccionia** [comment]
O conteúdo do texto já vem no shortcode -- às vezes, o local é contido nele (mas podemos puxá-lo para exibir na parte de cima).

A "categoria" não é puxada; não sei exatamente do que se trata (campo "área de atuação" do CRM?) e como exibi-la.

O resto deveria estar sendo importado e, agora, atualizado.
