### ISSUE TITLE
[ÁREA DE ASSOCIADOS] DESLOGAR AO CLICAR EM SAIR

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#134]
No momento quando clica em sair, direciona para uma tela do WP com um link para desconectar:

![Image](https://github.com/user-attachments/assets/337e6b02-5002-44f6-94b9-23adf3fd63a4)

- [x] O usuário deve realizar o logout sem o direcionamento

**Comment by thiagolamonte** [comment]
validação:

no novo.ethos, atualizar uma página e deslogar

**Comment by daphnemartinsba** [comment]
https://github.com/user-attachments/assets/53b8ed7b-54f5-4dcf-a29a-5c6f2d7e6347
