### ISSUE TITLE
[VALIDAÇÃO] LINKS, FORMULÁRIOS, IMAGENS e DIRECIONAMENTOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#137]
- [ ] se todos os links e blocos estão funcionando corretamente

- [ ] se há algum link direcionando para o site antigo e fazer o redirecionamento

- [ ] se há algum comportamento relativo ao preenchimento e edição de campos de formulários (se está enviando sem selecionar os campos obrigatórios, se aparece mensagem de erro quando não seleciona campos obrigatórios, enfim)
- [ ] se há imagens quebradas

1. Os retornos devem ser dados na issue, com exceções de casos que envolvam dados da empresa, nesses, deve ser dado pelo rocketchat

**Comment by marina-hacklab** [comment]
HOME:

- Bloco da agenda aparece vazio.
![image](https://github.com/user-attachments/assets/ea45c519-5d3a-4bde-8702-81bf3d7d533b)

Mensagem na edição da home: O bloco "tribe-widget-events-list" foi afetado por erros e pode não funcionar corretamente. Verifique as ferramentas para desenvolvedores para mais detalhes.

![image](https://github.com/user-attachments/assets/363e5757-4f0b-43d5-988b-4745966dc604)

O bloco não apresenta a opção de restauração de bloco.

- Link no botão "Mais publicações" redireciona para uma publicação específica ao invés de uma archive.
Endereço: https://novo.ethos.org.br/publicacao
Leva a: https://novo.ethos.org.br/publicacao/publicacao-1/

O redirecionamento não está sendo feito com um plugin.

**Comment by marina-hacklab** [comment]
- Link no botão "Mais projetos" redireciona para uma iniciativa específica ao invés de uma archive
Endereço: https://novo.ethos.org.br/iniciativa/
Leva a: https://novo.ethos.org.br/iniciativa-do-ethos-de-reconhecimento-das-empresas-comprometidas-com-combate-corrupcao-tem-recorde-de-inscricoes/

O redirecionamento não está sendo feito com um plugin.

- Grids de posts na área de Opinião não exibem nenhum resultado.
Blocos configurados corretamente para exibir o tipo-de-post Opinião, porém a archive desse tipo de post está vazia, então não há nenhum resultado para ser exibido.

**Comment by marina-hacklab** [comment]
SINGLES:

- Conteúdo do resumo aparece com um prefixo ETHOS INTEGRIDADE_
É possível que tenha a ver com a migração.

- Conteúdo do resumo aparece duplicado.
- Imagem em destaque repetida no corpo da matéria.
Sugestão: suprimir a primeira imagem em destaque que aparece grande no topo.

![image](https://github.com/user-attachments/assets/2cd82e27-e11b-4bc0-b8ca-4e52e385d906)

https://novo.ethos.org.br/instituto-ethos-lanca-o-programa-municipio-transparente-em-barcarena-e-paragominas-no-para/

**Comment by marina-hacklab** [comment]
PÁGINA INSTITUTO ETHOS:

- Links dos documentos pdf não funcionam como deveriam
Isso vale para os dois botões, "[Apresentação PDF do Instituto Ethos]" e "[Acesse o Código de Conduta do Ethos]"

Os documentos existem no site, mas ao tentar acessá-los a página não existe.
https://novo.ethos.org.br/apresentacao_institucional_2020-atualizacao_03-02/
https://novo.ethos.org.br/codigo-de-conduta_a4_links/

**Comment by marina-hacklab** [comment]
PÁGINA EQUIPE:

- Termo Read More aparece não traduzido
![image](https://github.com/user-attachments/assets/b1512467-307e-4fa3-b924-2cf2708ae77b)

- Ícone do Linkedin sem o link (em todos os integrantes da equipe)

- Usuários com a mesma imagem na aba "Gestão"
![image](https://github.com/user-attachments/assets/9f99d45a-686d-488f-9785-4b8e83ce9bd0)
Provávelmente essa questão é editorial

- Link para publicação sem documento
Na aba "Gestão", na parte dos links, o link em "Procedimento de Contratação" leva a publicação sem documento disponível.
https://novo.ethos.org.br/publicacao/procedimento-de-contas-a-pagar-do-instituto-ethos-2014/

- Links dos documentos pdf não funcionam como deveriam
Isso vale para dois links, "Código de Conduta" e "Procedimento para Análise de Casos de Associados"

Os documentos existem no site, mas ao tentar acessá-los a página não existe.
https://novo.ethos.org.br/codigo-de-conduta_a4_links/
https://novo.ethos.org.br/gestao/politicas-e-procedimentos/analise-de-associados-ethos/

**Comment by marina-hacklab** [comment]
PÁGINA ASSOCIADOS:

- Associados sem logo
![image](https://github.com/user-attachments/assets/de614174-5b4c-40bd-8ecb-0ebbffcd0624)

**Comment by marina-hacklab** [comment]
PÁGINA CONTATO:

O formulário de contato não marca todos os campos obrigatórios que não foram preenchidos quando o usuário tenta enviar o forumlário sem eles.

Exemplo completo de preenchimento:

Tentativa de enviar o formulário vazio
![image](https://github.com/user-attachments/assets/b522be20-5c17-4136-adc0-93ddf5312419)

Tentativa somente com o nome preenchido (não envia, não sai da página, mas não avisa a falta dos outros campos)
![image](https://github.com/user-attachments/assets/027f2d75-d09f-42e7-a53c-e8b8d21000af)

Com nome e e-mail, a mesma situação que acima
![image](https://github.com/user-attachments/assets/ca50df64-15a6-42ff-ac67-9f1fc75cdb05)

Com nome, e-mail e mensagem
![image](https://github.com/user-attachments/assets/ca15fb79-36b9-49ba-8b59-2f99762dff29)

Com todos os campos, sem o captcha preenchido
![image](https://github.com/user-attachments/assets/184a2930-f617-4824-bd1a-375b34eddd8b)

Com todos os campos + captcha o envio ocorre como esperado.

**Comment by marina-hacklab** [comment]
PÁGINA DIÁLOGOS ETHOS:

Na aba "Conexão Ethos", os links das edições realizadas levam a conteúdo que não encontro os equivalentes no site novo.
![image](https://github.com/user-attachments/assets/ca844159-447a-4358-b8c5-28d7258384bd)

https://novo.ethos.org.br/conteudo/conexoes/conexoes-ethos/conexoes-ethos-curitiba/
https://novo.ethos.org.br/conteudo/conexoes/conexoes-ethos/conexoes-ethos-belo-horizonte/

![image](https://github.com/user-attachments/assets/431bd7dd-1978-407e-81ef-f580d50d0318)

**Comment by marina-hacklab** [comment]
ARCHIVE POSICIONAMENTOS INSTITUCIONAIS:
https://novo.ethos.org.br/tipo-post/posicionamentos-institucionais/

Os filtros das abas não exibem nenhum posicionamento

**Comment by marina-hacklab** [comment]
ARCHIVE INICIATIVAS:
https://novo.ethos.org.br/iniciativas/

Os filtros das abas não exibem nenhuma iniciativa

**Comment by marina-hacklab** [comment]
ARCHIVES PUBLICAÇÕES:
https://novo.ethos.org.br/publicacoes/

Os filtros das abas não exibem nenhuma publicação

**Comment by marina-hacklab** [comment]
ARCHIVE NOTÍCIAS:
https://novo.ethos.org.br/tipo-post/noticias/

Filtros das abas não exibem nada

ARCHIVE OPINIÃO:
https://novo.ethos.org.br/tipo-post/opiniao/

Archive vazia

**Comment by marina-hacklab** [comment]
PÁGINA INDICADORES:
https://novo.ethos.org.br/indicadores/

Botões sem nenhum link que eu não sei para onde direcionar:

- Saiba o que sua empresa ganha com os Indicadores Ethos
- Entenda a estrutura do questionário
- Glossário
- Correlações com GRI iso265000 e cdp
- Informações sobre a publicação
- Passo a passo para acesso ao sistema e cadastro de usuários
- Correlações com 2ª geração dos indicadores Ethos

Botões que não funcionam mas redirecionam para a home:

- Baixe o questionário: https://novo.ethos.org.br/cedoc/indicadores-ethos-para-negocios-sustentaveis-e-responsaveis-v2014/#.VsIxA3IrLIU

Botões que levam a pdfs (mesmo problema que na página INSTITUTO ETHOS)

- [Manual para o módulo Guias Temáticos](https://novo.ethos.org.br/wp-content/uploads/2015/07/IndEthos_NSR_Sistema_GuiaTem%C3%A1tico.pdf)
- [Acesse o glossário](https://novo.ethos.org.br/wp-content/uploads/2017/06/Gloss%C3%A1rio-2017.pdf)

**Comment by marina-hacklab** [comment]
PÁGINA ETHOS SERVIÇOS:
https://novo.ethos.org.br/ethos-servicos/

- Botão sem link: botão "Solicitar" na aba "Consultoria"

**Comment by marinarcruz** [comment]
> HOME
> 
> * Grids de posts na área de Opinião não exibem nenhum resultado.
>   Blocos configurados corretamente para exibir o tipo-de-post Opinião, porém a archive desse tipo de post está vazia, então não há nenhum resultado para ser exibido.

Faremos atualização de plugins amanhã cedo para entender se ele volta, se tem alguma relação com o pods ou não.

**Comment by marinarcruz** [comment]
> SINGLES:
> 
> * Conteúdo do resumo aparece com um prefixo ETHOS INTEGRIDADE_
>   É possível que tenha a ver com a migração.
> * Conteúdo do resumo aparece duplicado.
> * Imagem em destaque repetida no corpo da matéria.
>   Sugestão: suprimir a primeira imagem em destaque que aparece grande no topo.
> 
> ![image](https://private-user-images.githubusercontent.com/156470059/355195177-2cd82e27-e11b-4bc0-b8ca-4e52e385d906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTE0NjcsIm5iZiI6MTcyMjg5MTE2NywicGF0aCI6Ii8xNTY0NzAwNTkvMzU1MTk1MTc3LTJjZDgyZTI3LWUxMWItNGJjMC1iOGNhLTRlNTJlMzg1ZDkwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQyMDUyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDg0MDBiNTczZjllZDg4N2RhNDY1YzA2ZTZmZDQ1N2Q5NGUxODE3ZTRlODdhMzQ3YTJmNjExMDc0OGMwOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FdNcXT1FuX_sOhfEpryNNpzkZR44xlWFp_mFm800V2I)
> 
> https://novo.ethos.org.br/instituto-ethos-lanca-o-programa-municipio-transparente-em-barcarena-e-paragominas-no-para/

Nesse caso aqui é ESSENCIAL alinhar com o cliente pois eles estão inserindo a imagem e a legenda tanto no painel do WP, como no corpo do post. Verifiquei esse link aqui e é o que parece. Antes disso, @marina-hacklab checa se

**Comment by marina-hacklab** [comment]
> SINGLES:
> 
>     * Conteúdo do resumo aparece com um prefixo ETHOS INTEGRIDADE_
>       É possível que tenha a ver com a migração.
> 
>     * Conteúdo do resumo aparece duplicado.
> 
>     * Imagem em destaque repetida no corpo da matéria.
>       Sugestão: suprimir a primeira imagem em destaque que aparece grande no topo.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/156470059/355195177-2cd82e27-e11b-4bc0-b8ca-4e52e385d906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNTg0NjEsIm5iZiI6MTcyNDM1ODE2MSwicGF0aCI6Ii8xNTY0NzAwNTkvMzU1MTk1MTc3LTJjZDgyZTI3LWUxMWItNGJjMC1iOGNhLTRlNTJlMzg1ZDkwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQyMDIyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOGQzNmVkNGY1YTQwYThjYjUwZmViOGEwMmYyNTNhOWM3NDI5ODU0ZTQxNmFhOGUxY2RiMWE4ZGJiOGM0MmZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tdKVVsVmM5Y-imgkKBXZkZFIh1MTK6TceUTqhWmJnsw)
> 
> https://novo.ethos.org.br/instituto-ethos-lanca-o-programa-municipio-transparente-em-barcarena-e-paragominas-no-para/

Problema das imagens replicadas e resumo com prefixo estranho nas singles segue acontecendo.
Acontece somente em notícias migradas, não nas publicadas após a migração.

Exemplo: https://www.ethos.org.br/medicos-listam-recomendacoes-para-evitar-doencas-em-meio-a-enchentes/

**Comment by marina-hacklab** [comment]
> PÁGINA INSTITUTO ETHOS:
> 
>     * Links dos documentos pdf não funcionam como deveriam
>       Isso vale para os dois botões, "[Apresentação PDF do Instituto Ethos]" e "[Acesse o Código de Conduta do Ethos]"
> 
> 
> Os documentos existem no site, mas ao tentar acessá-los a página não existe. https://novo.ethos.org.br/apresentacao_institucional_2020-atualizacao_03-02/ https://novo.ethos.org.br/codigo-de-conduta_a4_links/

Problema não corrigido

**Comment by marina-hacklab** [comment]
-    Link para publicação sem documento
    Na aba "Gestão", na parte dos links, o link em "Procedimento de Contratação" leva a publicação sem documento disponível.
    https://novo.ethos.org.br/publicacao/procedimento-de-contas-a-pagar-do-instituto-ethos-2014/

-    Links dos documentos pdf não funcionam como deveriam
    Isso vale para dois links, "Código de Conduta" e "Procedimento para Análise de Casos de Associados"

Os documentos existem no site, mas ao tentar acessá-los a página não existe.
https://novo.ethos.org.br/codigo-de-conduta_a4_links/
https://novo.ethos.org.br/gestao/politicas-e-procedimentos/analise-de-associados-ethos/

Problemas seguem ocorrendo

**Comment by marina-hacklab** [comment]
> PÁGINA INDICADORES: https://novo.ethos.org.br/indicadores/
> 
> Botões sem nenhum link que eu não sei para onde direcionar:
> 
>     * Saiba o que sua empresa ganha com os Indicadores Ethos
> 
>     * Entenda a estrutura do questionário
> 
>     * Glossário
> 
>     * Correlações com GRI iso265000 e cdp
> 
>     * Informações sobre a publicação
> 
>     * Passo a passo para acesso ao sistema e cadastro de usuários
> 
>     * Correlações com 2ª geração dos indicadores Ethos
> 
> 
> Botões que não funcionam mas redirecionam para a home:
> 
>     * Baixe o questionário: https://novo.ethos.org.br/cedoc/indicadores-ethos-para-negocios-sustentaveis-e-responsaveis-v2014/#.VsIxA3IrLIU
> 
> 
> Botões que levam a pdfs (mesmo problema que na página INSTITUTO ETHOS)
> 
>     * [Manual para o módulo Guias Temáticos](https://novo.ethos.org.br/wp-content/uploads/2015/07/IndEthos_NSR_Sistema_GuiaTem%C3%A1tico.pdf)
> 
>     * [Acesse o glossário](https://novo.ethos.org.br/wp-content/uploads/2017/06/Gloss%C3%A1rio-2017.pdf)

Problemas seguem acontecendo

**Comment by marina-hacklab** [comment]
> PÁGINA ETHOS SERVIÇOS: https://novo.ethos.org.br/ethos-servicos/
> 
>     * Botão sem link: botão "Solicitar" na aba "Consultoria"

Problema segue acontecendo. Na página no antigo.ethos não há nenhum botão similar para auxiliar a localizar para onde esse botão deveria levar

**Comment by caio-ascava** [comment]
Alguns comportamentos inesperados que a Marina apontou ainda persistem e outros foram ajustados.

- [ ] A página de contatos, teve uma melhoria, com o campo de nome e e-mail como obrigatórios agora.. Apenas o campo da mensagem não aparece esta necessidade (se necessário)

Porem, agora, nem preenchendo todos os campos é possível enviar pois aparece um erro, para tentar mais tarde.

- [ ] Em diálogos Ethos, conexão Ethos, os dois links que não possuíam direcionamentos agora segue para as respectivas singles. Porem as imagem nos destaques delas não carregam.

A duplicidade em imagem e subtítulo foram ajustadas e agora não identifiquei divergências.

- [ ] PDF de código de conduta e apresentação institucional não aparecem ainda.

- [ ] Na pagina equipe/governança, foram ajustadas as fotos e inseridos os links do LinkedIn no ícone

- [ ] No formulário de quero me associar, após o preenchimentos das informações e escolha do tipo de plano, aparece um erro

![Image](https://github.com/user-attachments/assets/231cc058-36c0-412a-bc5a-faa64c15209e)

- [ ] Ajustar botões indicados nos comentários da Marina

- Os filtros das abas das archives estão funcionando, embora com um pequeno atraso para carregar as imagens.

**Comment by filipesouzadev** [comment]
> ARCHIVE POSICIONAMENTOS INSTITUCIONAIS: https://novo.ethos.org.br/tipo-post/posicionamentos-institucionais/
> 
> Os filtros das abas não exibem nenhum posicionamento

@marina-hacklab sobre essa task, acabei fazendo um pequeno ajuste no código, mas, a questão apontada se dá por conta dos posts não estarem marcados em outras categorias.

**Comment by filipesouzadev** [comment]
> ethos-servicos/

Corrigido

**Comment by filipesouzadev** [comment]
> Alguns comportamentos inesperados que a Marina apontou ainda persistem e outros foram ajustados.
> 
> * [ ]  A página de contatos, teve uma melhoria, com o campo de nome e e-mail como obrigatórios agora.. Apenas o campo da mensagem não aparece esta necessidade (se necessário)
> 
> Porem, agora, nem preenchendo todos os campos é possível enviar pois aparece um erro, para tentar mais tarde.
> 
> * [ ]  Em diálogos Ethos, conexão Ethos, os dois links que não possuíam direcionamentos agora segue para as respectivas singles. Porem as imagem nos destaques delas não carregam.
> 
> A duplicidade em imagem e subtítulo foram ajustadas e agora não identifiquei divergências.
> 
> * [ ] 
>   [ ]  PDF de código de conduta e apresentação institucional não aparecem ainda.
>   [ ] 
>   [ ]  Na pagina equipe/governança, foram ajustadas as fotos e inseridos os links do LinkedIn no ícone
>   [ ] 
>   [ ]  No formulário de quero me associar, após o preenchimentos das informações e escolha do tipo de plano, aparece um erro
> 
> ![Image](https://github.com/user-attachments/assets/231cc058-36c0-412a-bc5a-faa64c15209e)
> 
> * * [ ] 
>     [ ]  Ajustar botões indicados nos comentários da Marina* Os filtros das abas das archives estão funcionando, embora com um pequeno atraso para carregar as imagens.

@caio-ascava não consegui reproduzir o erro do formulário quero me associar.

**Comment by filipesouzadev** [comment]
#report 
- sobre os botões com links que não funcionam:
identifiquei que muitos tem o link do arquivo, porém, ao acessar a mídia no site, vi que elas aparecem mas como um `.html`
acredito que esse problema tenha relação com a migração. não sei se seria o caso de rodar o script novamente.
- sobre o problema com o formulário de contato, eu não consegui progredir nisso, preciso de uma ajuda pra desbloquear.

**Comment by filipesouzadev** [comment]
@caio-ascava @brunosmartin estou passando essa para validação e removendo a questão sobre o formulário de contato pra criar uma issue específica disso.
