### ISSUE TITLE
[PARCERIAS/APOIO] Criar Widget

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#14]
O seguinte bloco é utilizado em diversas páginas/single:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/b887eb1a-cdba-4bc3-b267-b46d71f15dfe)

Por isso:

- [x] Sidebar para exibir parceiros será configurado em widget 

- [x] Utilizar metadado para determinar onde que aparecerá

Bloco se encontra presente também na home, layout:
https://www.figma.com/file/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=196-2&mode=design&t=fvqaDCWrjlv8agOo-0

**Comment by dioliviers** [comment]
- Inserido componente de widget, onde o usuário pode alterar os parceiros em 'Themas - layout-parts'
- Exibirá apenas nas singles e pages, menos nas archives conforme layout
- Para ativar basta selecionar a opção no post 
- O empilhamento ( mobile ) está seguindo o padrão do wordpress 

![Image](https://github.com/Ethos-ti/SiteEthos/assets/7771249/8a82b1f9-b8c6-4fb5-a2c1-f0c403de0fa7)

e logo apresentará no rodapé da página, segue o teste : 
https://ethos.hacklab.com.br/teste/

OBS: tem um outro metadado chamado : 
'parceiros' proveniente do ACF' : Verificar com @jacsonp ou @everaldomatias se existe algo a ser migrado neste metadado ou excluido.

**Comment by daphnemartinsba** [comment]
- [ ] Checkbox não aparece na home:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/6efedf3c-af42-4bdf-b7dd-71e1a8409bb1)

- [ ] Ajuste nos títulos e imagens:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/f2b39126-57c9-4901-b998-dc4c4dfff406)

**Comment by daphnemartinsba** [comment]
- [ ] Ajustar tamanhos dos ícones (alguns devem ficar menores, por exemplo, alcoa, hydro e etc):
Figma:
![image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/9d411f45-85a0-4d2d-9d13-2f966715e858)

Staging: 
![image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/a2396ad4-76ef-458c-8bbc-5d1452efb416)


- [ ] Separadores (traços que separam as parcerias) deve ser mais largo: No figma são um pouco menor que o limite do grid do corpo do texto, como na imagem acima

- [ ] Deixar texto em caixa alta (todo maiúsculo)

- [ ] Aumentar distância entre o bloco de parceria e o rodapé (utilizar tela proto de figma)
- [ ] Aumentar distância entre o bloco de parceria e o bloco acima (utilizar tela proto de figma)

https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=196-2&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=112%3A2

### Nova definição de layout:
- [ ] aplicar fonte x small nos textos:
- PARCERIA INSTITUCIONAL
- PARCERIA ESTRATÉGICA
- APOIO INSTITUCIONAL

**Comment by dioliviers** [comment]
Ajustado conforme solicitado 

OBS: O ícone da natura peguei no site de produção deles, porque no nosso é uma foto png que abraça todos os elementos, impossibilitando de capturar a imagem.

**Comment by daphnemartinsba** [comment]
- [ ] Bloco de parceiros não fica oculto quando marca a opção "Não"
