### ISSUE TITLE
[VALIDAÇÃO] ESTILOS E RESPONSIVIDADE

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#140]
- [ ] Revisar os estilos de todas as páginas
- [ ] Revisar a responsividade, mobile e tablet de todas as páginas

- Retornos devem ser ajustados e anotados aqui na issue

**Comment by barbaburns** [comment]
A home não esta pixel perfect. Muitos espaçamentos, embora proximos do figma, não estão exatos. 

- Editei pelo painel o Titulo "Projetos" de 3rem para 4rem em font-size e acrescentei um margin-top;
- adicionei os icones das 4 abas, tb pelo painel;
- adicionei margin-botom ao botão "Mais Projetos", pelo painel;
- adicionei margin-top ao titulo "Opinião";
- ajuste de bordas e padding dos botoes pelo arquivo overides/button.scss;
- ajuste para esconder o excerpt dos post-grid-blocks no arquivo blocks/posts-grid/style.scss;

**Comment by barbaburns** [comment]
Pagina Sobre:
- ajuste de margem em mobile;

Pagina Governança:
- ajustes de Titulos pelo painel;

**Comment by barbaburns** [comment]
Pagina Indicadores:

- ajuste de padding entre os tabs, pelo painel;

Pagina Guias tematicos:

- ajuste de margin-top em objects/post-content.scss


Paginas Iniciativas, Posicionamentos Institucionais, Publicações, Opinião e Noticias:

Os tabs estão sem os icones correspondentes. Daria pra trazer os icones para dentro do tema e adiciona-los via css.

**Comment by marina-hacklab** [comment]
HOME mobile:

- Quebra de linha no título "Projetos" na resolução de 360px:
![image](https://github.com/user-attachments/assets/bcf47580-e235-4271-9ee3-e357ab18418a)

No figma, com 360px de largura:
![image](https://github.com/user-attachments/assets/d0a7cc87-a6c8-47ba-bf27-648a9426e188)

- Isso está acontecendo pq as margens laterais estão maiores do que no layout, o grid todo está mais estreito

- Título "Opinião" descentralizado e com fonte menor do que no layout
![image](https://github.com/user-attachments/assets/f1f62cad-ef9e-4b3d-b921-60ab6216be6a)

Do figma:
![image](https://github.com/user-attachments/assets/433309d2-c389-408e-a3d7-c6ff58cade00)

- Na seção dos indicadores ethos a ordem dos elementos está invertida:
![image](https://github.com/user-attachments/assets/08a356db-af9a-4285-a990-62b84ba62c8b)

Do figma:
![image](https://github.com/user-attachments/assets/074a7672-0c52-461b-a083-5cc49f440e3c)

- Sem o rodapé da hacklab
![image](https://github.com/user-attachments/assets/f0ef9158-c7c1-4002-8486-bdbd3efc467c)

**Comment by marina-hacklab** [comment]
Página instituto ETHOS mobile: https://www.ethos.org.br/instituto-ethos/

Botões com quebra de linha: acontece por causa das margens laterais serem maiores do que as do layout. As margens se repetem pelo site inteiro.
![image](https://github.com/user-attachments/assets/d9569277-a3bf-4a3c-84c5-6b8e38e9e2f1)

Do figma:
![image](https://github.com/user-attachments/assets/58cd5e7f-a6fd-4094-87a7-d2332a94db96)

**Comment by marina-hacklab** [comment]
Página Prestação de contas: https://www.ethos.org.br/prestacao-de-contas/

Estilo do texto nos subitens das abas:
![image](https://github.com/user-attachments/assets/d3b878ea-98f4-412a-b29b-4f1c0bcdbc09)

Do figma:
![image](https://github.com/user-attachments/assets/85bf8a6d-2ba4-4aed-abec-674a91eea320)

**Comment by marina-hacklab** [comment]
Página Equipe/Governança mobile: https://www.ethos.org.br/equipe/

- Bloco de avatar variando de formato no mobile:
![image](https://github.com/user-attachments/assets/b2d60e59-c7e2-458e-a9e4-e3bac0d4549f)

- Título das colunas na aba Participação Social com quebra de linha:
![image](https://github.com/user-attachments/assets/333db659-123f-49e1-b99e-66c182a35893)

Esse ajuste exige código para ser feito pois o layout do desktop tem diferenças consideráveis em relação ao mobile. Não foi poissível se aproximar dos dois layouts usando os mesmos blocos para ambos.

Uma opção é ter um bloco de título adequado ao mobile acima das duas colunas e os títulos que já existem para cada coluna no desktop.
A solução ideal é rever toda a distribuição das colunas, que estão adequadas no painel para o desktop.

**Comment by marina-hacklab** [comment]
Página Contato:

Desktop:

- Alinhamento da caixa do reCaptcha no formulário:
![image](https://github.com/user-attachments/assets/539730e8-b72d-43e9-9601-e512e14be332)

Mobile:

- Alimento dos elementos abaixo da caixa da mensagem:
![image](https://github.com/user-attachments/assets/49114f0d-fc61-4326-89ed-8d2444407157)

Apesar de estar praticamente correspondendo ao layout, todos os elementos que não estavam previstos no layout juntos estão parecendo bagunçados.
Sugestão: aumentar o espaçamento superior da caixa do reCaptcha, avaliar a opção de centralizar o botão de Enviar.

**Comment by marina-hacklab** [comment]
Página Indicadores Ethos:

- Ícone do botão "Baixe o questionário" não aparece:
![image](https://github.com/user-attachments/assets/757962c9-d78f-4fe9-931b-84bb45a738fb)

No layout:
![image](https://github.com/user-attachments/assets/4455602e-4340-43b9-8e02-bb5e5bdf00eb)

Mobile:

- Só 3 das 4 abas estão acessíveis:
![image](https://github.com/user-attachments/assets/596efac9-c0d4-481f-b97b-66d2b512f71d)

Não há barra de rolagem para acessar os Docs de apoio.

**Comment by marina-hacklab** [comment]
Fonte dos números nas listas numeradas não corresponde à do layout.

Exemplo na página https://www.ethos.org.br/instituto-ethos/

**Comment by barbaburns** [comment]
Todas as modificações foram atualizadas no dev.ethos.org.br
