### ISSUE TITLE
[BLOCO DE GRID] ATUALIZAÇÃO DE POSTAGENS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#142]
Ao criar uma nova postagem e marcar como Opinião, por exemplo, o bloco de grid de OPINIÃO da HOME não lista a nova postagem, permanece listando as mesmas postagens, isso ocorre também com o BLOCO DE DESTAQUE, da HOME

- [x] Bloco de grid deve mostrar postagens mais recentes

**Comment by daphnemartinsba** [comment]
bloco demora 3600 segundos (= 1 hora) para atualizar

**Comment by thiagolamonte** [comment]
Transientes do bloco removidos pelo @leopiccionia , tema atualizado no ethos.hacklab. 

validação: 

criar um novo posts e selecionar as configuração do post para destaque da home ou opinião
