### ISSUE TITLE
[INDICADORES]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#15]
A página de indicadores possui 4 abas: questionário, sistema online, guias temáticos e docs de apoio

- [x] Abas devem ser um bloco gutenberg, utilizando o plugin Essential Blocks (confirmar se esse plugin será o utilizado mesmo)
- [x] utilizar widget parcerias/apoio #14 

- botão _Saiba o que sua empresa ganha com os Indicadores Ethos_ deve direcionar para: https://www3.ethos.org.br/wp-content/uploads/2014/10/Folder_site1.pdf

**Comment by barbaburns** [comment]
Na aba guias tematicos em um bloco de grid de posts que o @leopiccionia ira configurar melhor para ele se adequar ao layout.

**Comment by daphnemartinsba** [comment]
> Na aba guias tematicos em um bloco de grid de posts que o [@leopiccionia](https://github.com/leopiccionia) ira configurar melhor para ele se adequar ao layout.

@leopiccionia irá aplicar wide para o bloco de grid de posts

**Comment by leopiccionia** [comment]
As questões do grid foram destravadas por https://github.com/Ethos-ti/SiteEthos/commit/388317e43a2311ccbc6f88475e54090eaaf74ed3.

@barbaburns Depois do próximo release do tema, pode verificar se corrige o problema que estava tendo?

**Comment by caio-ascava** [comment]
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/c2cfc48a-0c47-4dff-a3c2-ef1ad2424b1c)

1. Ajuste de fonte e line-height
2. Ajuste de fonte e line-height
3. Não deve ser um botão
4. Diferença de layout
5. Quebra de linha de texto dentro do botão não deveria acontecer, sendo que nas imagens, estão S23 e Iphone 14 Pro (respectivamente) e são as maiores telas de mobile.
6. Não listado na imagem anexa, porem falta incluir o ícone de Baixar, dentro do botão Baixe o Conteúdo.

**Comment by barbaburns** [comment]
5. Quebra de linha de texto dentro do botão não deveria acontecer, sendo que nas imagens, estão S23 e Iphone 14 Pro (respectivamente) e são as maiores telas de mobile.

O botão do figma não segue o padrão dos botoes, precisa pedir pro pedro ajustar o layout.

**Comment by barbaburns** [comment]
os line-heights padrão estão sendo usados. precisa verificar com o pedro o pq dessa diferença esporadica nos valores de line-height.

**Comment by barbaburns** [comment]
10. os dois últimos botões nao são em formato de botão e o botões acima precisam ser aproximados.

Para poder fazer isso é preciso criar uma classe especifica para esses botoes o que é desencorajado. Sugiro conversarmos com o pedro para ele deixar todos como botoes.
