### ISSUE TITLE
[INTEGRAÇÃO CRM] Integrar SANDBOX no DEV

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#153]
Atualmente o sandbox está integrado ao ethos.hacklab, o ethos.hacklab não possui os cadastros do sandbox, possui os cadastros de teste e do CRM de produção 
- [x] Avaliação: puxar cadastros do sandbox para o dev
- [x] integração dev.ethos com sandbox

**Comment by jacsonp** [comment]
Comando executou, ficou faltando apenas os logs
