### ISSUE TITLE
[ANCORAGEM] Inserir âncora na postagem

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#155]
- [x] Inserir na documentação o como faz
- [x] Inserir ancoragem no post: https://www.ethos.org.br/desenvolvendo-modelos-de-negocios-antirracistas-a-realidade-da-mulher-negra-no-brasil/

**Comment by marina-hacklab** [comment]
Para validação: https://www.ethos.org.br/desenvolvendo-modelos-de-negocios-antirracistas-a-realidade-da-mulher-negra-no-brasil/

**Comment by daphnemartinsba** [comment]
- Ao clicar no número ao lado do nome o comportamento de âncora é disparado
-
