### ISSUE TITLE
[EVENTOS] Adequação do layout da página de certificação

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#165]
Página de emissão do certificado atualmente está assim:

![Image](https://github.com/user-attachments/assets/777c043d-f2e6-47d7-a2e1-356787340e4f)

https://www.ethos.org.br/evento/conferencia-ethos-360-belem-2024/?certificado

Não há layout previsto no figma.

Atualização:

- [ ] A página precisa exibir a estrutura de patrocinadores

Exemplo: https://www.ethos.org.br/certificado-de-presenca-na-conferencia-ethos-360-belem-2023/

**Comment by filipesouzadev** [comment]
A página já está estilizada, porém, estamos corrigindo um problema que não atualiza o css em produção.

**Comment by marina-hacklab** [comment]
@leopiccionia Tenho uma dúvida quanto a essa issue aqui estar fechada.

A página que deveria ser adequada ao exemplo não está batendo com o exemplo. Você sabe me dizer o que foi feito nessa issue especificamente?
Faltou o banner do evento e os patrocinadores do evento. Está sendo exibido no rodapé os do site.

Essa aqui é uma entrega a ser feita junto com a do certificado para impressão.

**Comment by leopiccionia** [comment]
A issue está movida para Done, eu só a fechei no GitHub.
