### ISSUE TITLE
[EVENTOS] Estilização do certificado

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#166]
Pedido chegou pelo e-mail.

Cliente gostaria que o certificado fosse mais similar ao modelo antigo. Sentido horizontal e com uma única página.

Exemplo do site antigo:

![Image](https://github.com/user-attachments/assets/2c0b1e2a-a3dc-4e43-8e44-32e0a2ca7d3c)

Exemplo do site atual:

![Image](https://github.com/user-attachments/assets/d2e66eb2-9e72-4f28-bb3f-2d53795390a4)

**Comment by filipesouzadev** [comment]
melhorei a página para impressão do certificado, porém, não consegui ainda exibir os parceiro no certificado.

**Comment by marina-hacklab** [comment]
Envolve os ajustes pendentes na página da https://github.com/Ethos-ti/SiteEthos/issues/166

- [ ] Possibilitar a exibição do banner do evento
- [ ] Exibir os parceiros do evento, não os patrocinadores do instituto, no rodapé da página
