### ISSUE TITLE
[EVENTOS] Dados do WP diferentes do CRM

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#169]
Data e horário dos eventos no WP não estão de acordo com o CRM

**Comment by everaldomatias** [comment]
@marina-hacklab finalizei a investigação e o que aconteceu é que as datas dos eventos foram alteradas no CRM depois que ele foi importado para o WP. O @leopiccionia já implementou um método de sincronização que vai observar daqui para frente essas alterações.

Então, esses eventos com datas diferentes, podem ser corrigidos no WP e a sugestão é olhar apenas os eventos que ainda vão acontecer (sugiro olhar de 31/07 até o último evento).

Qualquer dúvida é só chamar.
