### ISSUE TITLE
[MIGRAÇÃO] Eventos do Events Calendar

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#17]

**Comment by everaldomatias** [comment]
# Eventos

- Todos eventos em prod são “únicos”
- Os eventos são do CPT cedoc com a taxonomia “categoria” com o termo “agenda”
- O formato de data deve ser atualizado para o The Events Calendar, atualmente o campo de data e horário são campos separados e no plugin é um campo start_date e end_date

### Metadados

**Dev > The events calendar**

data-do-evento > `_EventStartDate` e `_EventStartDate`

horario > `_EventStartDate` e `_EventStartDate`

local > `_EventVenueID` (id do local, verificar como é esse relacionamento)

curso > (campo personalizado que indica se é um curso ou não)

carga_horaria_total > (campo personalizado com a carga horária do curso)

inscricoes > (campo personalizado com link para local de inscrição) `_EventExternalURL`

saiba_mais > (campo personalizado com link externo)

informacoes_complementares > (campo personalizado de texto)

**Comment by everaldomatias** [comment]
Os scripts necessários foram criados e estão no dev para teste (para a equipe de infra rodar os comandos).

Lembrando que eventos (Cedoc com termo Agenda) que não possuem datas, não são migrados e ficam com um metadado de rastreio para a localização, caso necessário.

**Comment by marinarcruz** [comment]
18/06: os eventos que estão sem data, migraremos com uma data antiga e informaremos o cliente que estão nessa configuração, em rascunhos. São cerca de 100 eventos. Informar o cliente por email.

**Comment by daphnemartinsba** [comment]
migração foi realizada 15 de maio e o ajuste foi realizado no dia 20 de maio

**Comment by marinarcruz** [comment]
será preciso refazer o script para coletar os que não foram validados pois estavam dando erro na single.

**Comment by marinarcruz** [comment]
15/07: será preciso fazer o pente fino nos eventos após 20/05, mas também será preciso rodar os scripts novamente pois os eventos foram migrados com um bug: quando a página é atualizada no painel o conteúdo some.
Informar o cliente de não atualizar os eventos antigos até a correção desse bug.

**Comment by daphnemartinsba** [comment]
informações: eventos sem horário foram migrados 00 horas na data de início e 23:59:59 na data de término

**Comment by marinarcruz** [comment]
17/7: Jacson debugou o problema. Era a falta da tag "p" .
Eve vai corrigir e depois Jacson roda o script novamente.

**Comment by daphnemartinsba** [comment]
- Validar principalmente eventos que possuem mais de um parágrafo, eram eles que perdiam o conteúdo ao ter a postagem atualizada

**Comment by caio-ascava** [comment]
![Image](https://github.com/user-attachments/assets/651ab3ce-8b4f-453e-ad81-ed61e6234dc3)

![Image](https://github.com/user-attachments/assets/ef210bd8-0e9b-4d15-a0dd-e3490ad8dcc8)

![Image](https://github.com/user-attachments/assets/4112ae1e-a92b-4646-abe6-ffe8502036f7)

**Comment by caio-ascava** [comment]
Validado, de acordo, com os casos abaixo:
evento/cultura-de-integridade-na-gestao-de-pessoas/

1. https://ethos.hacklab.com.br/evento/curso-transformacao-cultural-2/
2. https://ethos.hacklab.com.br/evento/cultura-de-integridade-na-gestao-de-pessoas/
3. https://ethos.hacklab.com.br/evento/curso-trabalhando-a-cultura-organizacional-e-integridade-em-negocios-2/
4. https://ethos.hacklab.com.br/evento/roda-de-dialogo-o-papel-das-empresas-na-saude-mental-dos-empregades/
