### ISSUE TITLE
[Notícias] Archive de notícias exibe o mesmo conteúdo em todas as páginas

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#170]
Demanda chegou via WhatsApp.

A archive de Notícias exibe as mesmas notícias em todas as páginas.

https://www.ethos.org.br/tipo-post/noticias/

![Image](https://github.com/user-attachments/assets/b8c8a90a-ece8-489c-a1fa-5d3df8152117)

https://www.ethos.org.br/tipo-post/noticias/page/2/

![Image](https://github.com/user-attachments/assets/de46aa11-664a-443d-b124-570d149e7e69)

**Comment by marina-hacklab** [comment]
Problema também acontece em: 
- Opinião: https://www.ethos.org.br/tipo-post/opiniao/
- Posicionamentos institucionais: https://www.ethos.org.br/tipo-post/posicionamentos-institucionais/

Não acontece em:
- Iniciativas: https://www.ethos.org.br/iniciativas/
- Publicações: https://www.ethos.org.br/publicacoes/

Avalio que é nas archives dos tipos de post

**Comment by filipesouzadev** [comment]
@marina-hacklab para testes e validação:

https://dev.ethos.org.br/tipo-post/noticias/page/2/
