### ISSUE TITLE
[PAGAMENTOS] Páginas de pagamentos apresentando erro

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#171]
As pessoas estão tentando efetuar o pagamento referente a compra de ingresso para a conferência Ethos SP é quando clicam no link aparece uma página de erro.

Link: https://www.ethos.org.br/conteudo/acesso-a-pagamento/?pagid=5d48285f-595e-ef11-bfe4-6045bd38999e&xy=AE420BA43C3CDDCCC4DBEFA4FE5B7B3A 

![Image](https://github.com/user-attachments/assets/3acb5e33-9a9f-4124-bd6c-6530bd6971fe)

Mensagem de erro:
Warning: Undefined array key "pagid" in /home/site/wwwroot/wp-content/plugins/ethos-associados/ethos-associados.php on line 2759

**Comment by jacsonp** [comment]
fixed on 411d93f04bce55f6d6eaaa26be75e8fa5edc6f1e
