### ISSUE TITLE
[ CONTATO ]  Bug no envio do formulário de contato

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#172]
O formulário de contato não está sendo enviado:

![Image](https://github.com/user-attachments/assets/c729e262-7c0f-4b9d-acb2-068d1daeeb35)

tentei inclusive trocar as chaves recaptcha em dev para v2 e inverter para v3 mas ainda assim o envio não é feito.

**Comment by caio-ascava** [comment]
Tentativa teste de contato enviada com sucesso
