### ISSUE TITLE
[INTEGRAÇÃO CRM] - Eventos com vagas esgotadas no site

### ISSUE THREAD

**Issue by everaldomatias** [Ethos-ti/SiteEthos#174]
Mensagens trocadas com o cliente:

Primeira mensagem:
"Boa tarde, como vai??

Gostaria de um auxílio, pois estamos recebendo informações das associadas ao se inscrever em um evento que as vagas estão esgotadas, não sendo possível fazer a inscrição. Está tudo certo no CRM, como sempre fizemos. Segue o print e evento criado no CRM para análise."

Pedi mais informações:
"Bom dia, Iasmin! Tudo bem?

Gostaria de te pedir algumas informações adicionais sobre o problema para auxiliar na investigação que estamos realizando.

No site antigo, quando esgotavam-se as vagas para um evento deixava de ser possível realizar novas inscrições?
O acompanhamento dessas vagas está sendo feito pelo CRM?

Essas informações nos ajudarão bastante! Agradeço desde já."

A resposta dela:
"Olá, Marina!

Bom dia, tudo e você?

Isso, no site antigo, em teorias as vagas seriam esgotadas, coisa que nunca aconteceu, pelo menos em nossa área.

O acompanhamento das inscrições e quantidades são feitas no CRM, porém, criei o evento tem poucos dias e não tinha nenhuma inscrição e já está como vagas esgotadas."

**Comment by everaldomatias** [comment]
Link do evento no CRM (produção):

***/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&pagetype=entityrecord&etn=fut_projeto&id=d354c8e3-ce63-ef11-a670-6045bd3ba26c

**Comment by marinarcruz** [comment]
fazer teste em dev, para evento gratuito, se após esgotarem-se as vagas não aparece a opção de inscrever-se mais.
