### ISSUE TITLE
Permitir edição de evento importado do CRM no WP

### ISSUE THREAD

**Issue by laurahacklab** [Ethos-ti/SiteEthos#176]
Recebemos um novo e-mail sobre o fluxo de eventos/páginas de cursos no qual o Lucas relatou mais uma vez um problema sobre o qual já atuamos e orientamos eles, que é o dos eventos aparecendo duplicados na agenda.

Porém nesse novo e-mail ele confirma que eles estão criando as páginas duplicadas pq não gostam da forma como elas vem criadas automaticamente do CRM. De acordo com ele as páginas que vem da integração não podem ser customizadas o suficiente para atender os critérios da comunicação.

Porém novamente as páginas criadas pela comunicação não tem a funcionalidade de inscrição, o que é um problema para todas as outras equipes.

Exemplo:
Página do CRM: https://www.ethos.org.br/evento/gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade-2024/
Página da comunicação: https://www.ethos.org.br/evento/curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade-2/

A solução dele foi colocar um botão de inscrição que leva à página correta.

Eles querem que eventos específicos criados pelo CRM que tenham repetição não apareçam na agenda.

**Comment by marinarcruz** [comment]
Diagnóstico: atualmente é criado um evento no CRM e o WP puxa esse evento para publicar no site. Esse evento criado no WP não é possível de ser editado. Sendo assim, o cliente cria outro evento, somente no WP, para atender as necessidades editoriais deles. 
Solução: tornar a página que é puxada pelo CRM no WP em página editável, para que eles não precisem criar outra página.

**Comment by everaldomatias** [comment]
Ajustes/modificações realizadas:

- Na importação do evento, o conteúdo do evento é salvo no content do evendo no WP;
- Uma vez que o conteúdo é atualizado no WP, a sincronização não vai mais salvar o conteúdo do CRM no content do evento no WP;
- Quando o content é preenchido, seja pela sincronização ou manualmente, os dados do CRM que anteriormente eram exibidos pelo shortcode, agora é omitido. Entendemos que se o content sofre alteração no evento do WP, a equipe editorial deseja priorizar esse conteúdo.

Para testar:

- No ambiente dev, é preciso criar um evento no CRM Sandbox e aguardar a sincronização.
- Com a sincronização finalizada, verificar se o conteúdo criado no CRM é exibido na single do evento.
- Fazer uma alteração no content do evento no WP e verificar se esse é exibido e o conteúdo do CRM ignorado.
