### ISSUE TITLE
Problemas com eventos recorrentes

### ISSUE THREAD

**Issue by laurahacklab** [Ethos-ti/SiteEthos#177]
Sobre os eventos recorrentes:

- Eventos com informações conflitantes: https://www.ethos.org.br/evento/plantoes-de-duvidas-indicadores-ethos-agosto-2024-2/2024-08-30/

Os eventos recorrentes estão sendo criados com as datas corretas para os novos encontros, mas as informações na página não são atualizadas. No exemplo, o evento está com a data correta para o dia 30, mas na página ele tem vários textos que falam dia 12;

- Erro de digitação no dia da semana:

Ao invés de segunda-feira os eventos puxam uma string que diz Seguda-feira, precisa de correção;

- "Além disso, se for possível, acho que seria interessante também alterar “Tipo do evento” para “Recorrência”, fica mais claro para os usuários do que se trata o campo."

Nas informações iniciais da página, na parte superior, há a informação Tipo de evento, que hoje é "Semanal". Essa informação, se não estou enganada, vem diretamente no CRM. Aí precisaríamos avaliar se é um novo desenvolvimento por ser uma mudança nas taxonomias, se vamos realizar, etc...

**Comment by marina-hacklab** [comment]
Caso o terceiro ponto seja um novo desenvolvimento é só avisar que fazemos uma issue separada.

**Comment by everaldomatias** [comment]
- Correção da string "seguda"
- Alteração de "tipo do evento" para "recorrência"
- Tradução das strings que estavam hardcoded na single de eventos
