### ISSUE TITLE
Adicionar suporte para criação de eventos recorrentes pelo site integrados com o CRM

### ISSUE THREAD

**Issue by laurahacklab** [Ethos-ti/SiteEthos#178]
Há um evento criado pelo Lucas com 4 repetições, dias 17, 18, 19 e 20. Eles só está criando no dia 17 e 18.

Links dos que foram criados:
https://www.ethos.org.br/evento/curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade-2/2024-09-17/
https://www.ethos.org.br/evento/curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade-2/2024-09-18/

Links que deveriam ser criados mas só redirecionam aos dias anteriores e não aparecem na agenda:
https://www.ethos.org.br/evento/curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade-2/2024-09-19/
https://www.ethos.org.br/evento/curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade-2/2024-09-20/

Agora adicionaram também um pedido para que os eventos recorrentes não sejam criados como uma série de páginas separadas, e sim uma única página que apresenta a informação para todos os dias.

"Percebi que o dia 17 e 18 possuem URLs diferentes. Seria interessante para a gente que a URL permanecesse a mesma, uma única página apresentando todos dias e horários (com os dias separados na agenda do site, como está o 17e e 18). Isso porque temos campanhas que irão rodar levando tráfego para essa página de curso"

**Comment by marinarcruz** [comment]
Investigar a criação de eventos recorrentes pelo CRM e como é feita a integração com o plugin Events Calendar. O cliente quer que mesmo com datas diferentes, a URL seja uma só. É possível, pelo plugin, que seja uma só com /all, mas precisamos fazer ajustes de css. Importante entender que o cliente precisará editar o evento quando for puxado pelo WP. Relacionado com a issue

**Comment by marinarcruz** [comment]
Descobrir como são criados eventos recorrentes no CRM, investigar como são exibidos no Events Calendar

**Comment by everaldomatias** [comment]
Fiz uma investigação nos itens apontados nessa issue e sobre o item

- [ ] Há um evento criado pelo Lucas com 4 repetições, dias 17, 18, 19 e 20. Eles só está criando no dia 17 e 18.

Como esse é um evento que foi ciado diretamente no WP, fiz um teste em dev, criei o evento [(Teste) – Curso | Gestão de Riscos ASG (ESG) no Contexto da Sustentabilidade](https://dev.ethos.org.br/evento/teste-curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade/) e funcionou normalmente. Acredito que na criação das séries (recorrência) do evento, ocorreu algum problema.

Minha sugestão é orientar a pessoa responsável pelos eventos, de como deve ser feito.

Os outros pontos que vejo nessa issue são:

- [ ] Redirecionar todos eventos da série para o evento principal (@marinarcruz @marina-hacklab temos outra issue para isso?)
- [ ] Descobrir como são criados eventos recorrentes no CRM
- [ ] Investigar como são exibidos no Events Calendar os eventos recorrentes criados no CRM e importados para o WP

**Comment by everaldomatias** [comment]
- [ ] Descobrir como são criados eventos recorrentes no CRM

Fiz uma investigação no CRM, tanto em eventos que já existem, como criando novos e não encontrei uma forma de apontar que ele é um evento recorrente. A únca informação presente é a data de início e término, mas nenhum campo específico sobre recorrência, nem campo para adicionar exceção.

**Comment by marinarcruz** [comment]
Validar checando se o formulário de inscrição aparece em todas as ocorrências dos eventos no WP.

**Comment by marina-hacklab** [comment]
No evento criado para teste, não aparece formulário de inscrição em nenhuma repetição

https://dev.ethos.org.br/evento/teste-curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade/2024-09-19/
https://dev.ethos.org.br/evento/teste-curso-gestao-de-riscos-asg-esg-no-contexto-da-sustentabilidade/2024-09-20/

**Comment by marina-hacklab** [comment]
https://dev.ethos.org.br/evento/teste-hl-eventos-recorrentes/

Evento criado no CRM para teste

**Comment by caio-ascava** [comment]
foi realizada a criação de um evento pago através do CRM produção. Após realizar uma etapa de sincronização manual com o WP, o evento apareceu na single  de eventos.  Ao realizar edição  do evento no WP, para tornar recorrente, foi observado que:

ao gerar uma recorrência no WP, você só consegue se inscrever uma vez para um evento que terá recorrência semanal.... você tornar um evento recorrente, mesmo que inserindo 4 datas diferentes ele não vai considerar 4 eventos distintos, mas um unico evento que ocorrerá em 4 datas diferentes.

Quando verificada a agenda, apesar de recorrência inserida, o que aparece no calendário é apenas em uma única data. 

![Image](https://github.com/user-attachments/assets/f2daff04-13ca-4382-a651-08808f132d48)
![Image](https://github.com/user-attachments/assets/081c8df9-24f4-440f-9399-e037c262132c)

**Comment by marinarcruz** [comment]
Orientar cliente de inserir o link do formulário da inscrição em todos os demais eventos recorrentes.

**Comment by marinarcruz** [comment]
Foi identificada que a criação de eventos deve ser feita pelo CRM, sem a indicação de recorrência. Depois, quando este é importado para o WP, deve ser configurado com data única com recorrência a partir do painel WP. Atualizar documentação. @marina-hacklab 

Outro problema a ser investigado é relacionado à issue 201, relacionado aos formulários de inscrição não estarem sendo visíveis nos eventos.

**Comment by marina-hacklab** [comment]
Documentação entregue ao cliente via e-mail.
