### ISSUE TITLE
[CABEÇALHO] Botões ENTRAR, QUERO ME ASSOCIAR, ÁREA DE ASSOCIADO e CAMPO DE BUSCA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#18]
Regra de exibição dos botões:

- [x] Quando deslogado: acesso ao botão entrar e quero me associar
- [x] Quando logado: acesso ao botão área de associado
- [x] Quando logado: botão área de associados deve ter dropdown que contenha a opção sair:

- dropdown deve abrir com o clique em cima da seta

- [x] Ao clicar na lupa, deve abrir o campo de busca

https://www.figma.com/design/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=216-11&t=i6eJTKPxX6oBZJVL-0

**Comment by caio-ascava** [comment]
qdo logado, ok, ele deve estar cobrindo o botão área do associado... mas qdo deslogado ele sobrepõe o botão "quero me associar"

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/70761ba9-a676-43e6-9464-c087fbb54b4a)

**Comment by caio-ascava** [comment]
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/d0aa2182-56c4-4f11-aeab-d6759f9aac0b)
