### ISSUE TITLE
[EVENTOS] Links de inscrição gerado no CRM não recireciona para o evento corretamente

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#180]
Os links que recebemos são os que o CRM gera quando um evento é criado, que deveriam redirecionar para a página do evento no site.
- Primeiro link:
https://www.ethos.org.br/conteudo/inscricao-evento?id=1388
Esse funciona normalmente para mim.
Redireciona para https://www.ethos.org.br/evento/plantoes-de-duvidas-indicadores-ethos-setembro-2024/2024-09-09/
Pedi para ela testar novamente e ela diz que ele não funciona, mas que consegue acessar o evento pela agenda.

- Segundo link:
https://www.ethos.org.br/conteudo/inscricao-evento?id=1382
Esse dá numa 404 para mim.
Com o nome do evento eu consegui localizar ele no site: https://www.ethos.org.br/evento/plantoes-de-duvidas-indicadores-ethos-agosto-2024-2/2024-08-30/
Esse é um evento recorrente, e parece que eles criam primeiro no CRM e depois no Wordpress.

- Terceiro link:
https://www.ethos.org.br/inscricao-evento/?id=1389
Esse não está funcionando, leva a uma 404, porém localizei no site o evento que parece ser equivalente e é esse aqui: https://www.ethos.org.br/evento/roda-de-dialogo-papel-das-empresas-no-processo-eleitoral/

**Comment by leopiccionia** [comment]
Em alguns casos, o 404 ocorre porque o evento ainda não puxou todos os dados necessários do CRM. Para puxar os dados imediatamente, adicionei um botão "Sync with CRM" (talvez traduza o termo) na sidebar de edição do evento.

![image](https://github.com/user-attachments/assets/37b71678-bb8f-419c-9a46-b7f82b2bd4a2)
