### ISSUE TITLE
[EVENTOS] Vouchers não funcionando

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#181]
Problema para realizar inscrições no evento Conferência Ethos 360 SP:
https://www.ethos.org.br/evento/conferencia-ethos-360-sao-paulo-2024/

Quando utilizam um voucher não é possível concluir a inscrição no evento.
Voucher usado para teste: DS-Voucher para teste-E

Os vouchers não são necessariamente vinculados a um CNPJ ou um CPF. O voucher criado para teste, por exemplo, não tem nenhuma limitação.

**Comment by jacsonp** [comment]
Corrigido no ethos-associados
