### ISSUE TITLE
[AVATAR] Ajuste no bloco de avatar na página da Equipe

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#182]
Na página
https://www.ethos.org.br/equipe/

O formato do bloco com o avatar está variando com a imagem utilizada.
Exemplo enviado pelo cliente: Benilda Brito

![Image](https://github.com/user-attachments/assets/fec96ed2-509a-401e-8804-52b3ffbfab95)

Outros exemplos:

![Image](https://github.com/user-attachments/assets/8e06c682-3f4d-43ae-bf61-995ff12a7a51)

**Comment by filipesouzadev** [comment]
Esse ajuste já havia sido feito na issue #147 e validado, porém, foi removido em algum momento.
Refiz o ajuste de forma ainda mais específica, mas fica aqui o comentário para tomarmos cuidado ao remover ou alterar css.
