### ISSUE TITLE
[EVENTOS] Taxonomia "Categorias de Eventos" sem informação na maioria dos eventos

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#185]
O problema relatado por e-mail foi que o filtro por categorias da agenda não parece estar funcionando.
Página enviada: https://www.ethos.org.br/agenda/categoria/cursos/

Os filtros seguem a taxonomia Categorias de Eventos. Porém não há nenhuma das categorias atribuída aos eventos no site.
Abaixo está a lista de categorias. Observe que só há 4 eventos atribuídos a categorias.

![Image](https://github.com/user-attachments/assets/f268881f-4600-4181-a253-4db64036cd22)

Levantamos 3 possibilidades:

a) Essa informação é nova e nunca existiu;
b) Faltou migrar essa informação;
c) Ela viria do CRM mas não está sendo sincronizada.

**Comment by marinarcruz** [comment]
Precisamos checar no banco de dados para checar se os posts estão vindo com os dados corretos de "cursos". O script que desenvolvemos trasforma os metadados em categoria "cursos". Checar se o script foi rodado corretamente para cursos futuros.

**Comment by everaldomatias** [comment]
Criei um script que percorre todos os eventos com o metadado "curso" e marca o termo "Cursos" da taxonomia "tribe_events_cat".

Para rodar o script, rodar o comando WP CLI:

`wp modify-posts q:post_type=tribe_events q:post_status=draft,private,publish q:meta_query=curso:1 q:suppress_filters fn:ethos\\set_events_courses`

**Comment by everaldomatias** [comment]
Para validar, observar a quantidade de eventos (The Events Calendar) marcado com o termo "Cursos" da taxonomia "tribe_events_cat".

![image](https://github.com/user-attachments/assets/b4fb5ded-5c3d-4c69-a64a-f7824a84d219)

**Comment by caio-ascava** [comment]
Validação concluída!
