### ISSUE TITLE
[ACESSIBILIDADE] Reposicionamento do ícone do plugin de acessibilidade

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#188]
O ícone do plugin de acessibilidade está soprepondo a lupa da pesquisa em monitores menores.

A sugestão do cliente foi posicionar ele mais ao centro da página, mas cabe avaliação.

**Comment by dioliviers** [comment]
Boa tarde marinaa ! 

Olha fiz alguns testes em alguns monitores, fiz uma leitura no código também, e ele está em uma posição relativa a lupa e o input da lupa, ou seja ela não se sobrepoe nunca a lupa sempre respeita o espaço reservado da mesma, contudo fiz alguns testes em mobile e em algumas resoluções de notebook e não foi evidenciado o problema. Caso realmente ocorre, poderia fazer a gentileza de pedir a resolução testada ? Mas de todo modo não há possibilidade de sobrepor a lupa de pesquisa por conta da configuração inseria no css. 

Segue algumas prints 

![Captura de tela de 2024-09-16 16-54-29](https://github.com/user-attachments/assets/391deeae-076a-4b10-a7ab-1f21166d4973)
![Captura de tela de 2024-09-16 16-52-36](https://github.com/user-attachments/assets/52e8a81d-472b-4b93-b6cd-bfb4342cc819)
![Captura de tela de 2024-09-16 16-52-26](https://github.com/user-attachments/assets/99ca94e9-28ae-4e4c-bf7b-7c0e04d97029)
![Captura de tela de 2024-09-16 16-33-23](https://github.com/user-attachments/assets/c7709536-cf65-4f6c-b067-64f83e738e58)
![iphone14pro](https://github.com/user-attachments/assets/8bd131dd-df9a-40d9-b2ec-d357bd4390e9)
![Captura de tela de 2024-09-16 16-32-26](https://github.com/user-attachments/assets/fae3a3c0-6142-4b2a-b240-e23190968a1f)

**Comment by dioliviers** [comment]
![image](https://github.com/user-attachments/assets/4dc87aca-7361-4243-bfea-78c0434c8355)
![image](https://github.com/user-attachments/assets/bb145dc8-2a65-463b-a8a8-4667571c4443)

**Comment by dioliviers** [comment]
Obs: está torto porquê o inspetor de elementos está aberto.

**Comment by caio-ascava** [comment]
Resolução de tela 1024 x 768
![Image](https://github.com/user-attachments/assets/f0a0d88e-6441-418f-bc88-7f8dba247979)

**Comment by caio-ascava** [comment]
Iphone 7 
![Image](https://github.com/user-attachments/assets/f235a7f3-86d1-465f-a419-c5bae2ae97bc)
