### ISSUE TITLE
[HOME] Alteração de logos cabeçalho e rodapé

### ISSUE THREAD

**Issue by marinarcruz** [Ethos-ti/SiteEthos#189]
Alterar as logos de todo o tema:

- no cabeçalho vai a logo azul, sem a tagline
- no rodapé vai a logo em branco, com a tagline

Documentos estão disponíveis na pasta do projeto "envio".

Fazer em dev para virar o commit às 8h na quarta, dia 18/9.

**Comment by thiagolamonte** [comment]
Não consegui subir imagens no ambiente de DEV. Teste do local: 

![Image](https://github.com/user-attachments/assets/fc7ff5da-f34c-4cfd-9254-4f5251841ae3)

**Comment by thiagolamonte** [comment]
Novos logos aplicados em PROD 

![Image](https://github.com/user-attachments/assets/5b278dad-474f-4b39-a844-3d606196a7a8)
