### ISSUE TITLE
[EVENTOS] [ARCHIVES] Migração dos eventos de Grupos de Trabalho do site antigo para a Categoria de Eventos "Grupos de Trabalho"

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#194]
No site atual, a archive de eventos da Categoria de Eventos "Grupos de Trabalho" aparece vazia:

https://dev.ethos.org.br/agenda/categoria/grupos-de-trabalhos/

Ela aparece vazia pois não há nenhum evento nessa taxonomia.

- [x] Fazer um script para migrar os Grupos de Trabalho do site antigo para a taxonomia no site atual, dentro do Events Calendar

Os grupos de trabalho no site antigo estão somente identificados com a taxonomia "Agenda" no cedoc e precisam ser filtrados pelo nome (que comece ou contenha "Grupo de Trabalho")

- [ ] atualizar documentação @marina-hacklab

**Comment by everaldomatias** [comment]
Script feito.

Para validar, é necessário que os plugins abaixo estejam nas seguintes versões:

`hacklab/ dev utils` >= 1.0.6
`Ethos Migration Plugin` >= 0.5.4

E é necessário rodar o comando:

```sh
wp modify-posts q:post_type=tribe_events q:post_status=draft,private,publish q:suppress_filters=1 q:s=grupo%de%trabalho fn:ethos\\set_grupos_de_trabalhos_term
```

**Comment by marina-hacklab** [comment]
Validada.

Página da agenda de grupos de trabalho já exibe conteúdo como esperado: https://www.ethos.org.br/agenda/categoria/grupos-de-trabalhos/

**Comment by laurahacklab** [comment]
@marinarcruz Qual o motivo da reabertura dessa issue?
