### ISSUE TITLE
[INFRA] Redirecionar links do rodapé do site Indicadores Ethos para o site atual

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#199]
No site https://indicadoresethos.ethos.org.br/

Os links do rodapé tem www3 e levam ao site antigo.

Não temos acesso ao painel desse site, o redirecionamento precisa ser feito pela infra.

**Comment by laurahacklab** [comment]
@marina-hacklab Feito através das regras de redirecionamento do cloudflare:
![Screenshot 2024-09-26 at 12-39-54 Regras Regras de redirecionamento ethos org br Instituto Ethos Cloudflare](https://github.com/user-attachments/assets/11409c74-3d37-4fa9-a538-f4b4d6cb10b1)

e com alteração do dns:
![Screenshot 2024-09-26 at 12-35-49 DNS Registros ethos org br Instituto Ethos Cloudflare](https://github.com/user-attachments/assets/078a2458-d1f8-4ce1-8143-554ea126334f)

testei usando esse link: https://www3.ethos.org.br/conteudo/indicadores-ethos-publicacoes
@caio-ascava poderia validar?

**Comment by caio-ascava** [comment]
Validação concluída com a verificação do redirecionamento para site atual quando clicar em indicadores ethos do site antigo.
