### ISSUE TITLE
[MIGRAÇÃO] Definir arquitetura de informação para migração dos dados.

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#2]
- [x] Definir arquitetura de informação para migração dos dados.

**Comment by marinarcruz** [comment]
https://docs.google.com/spreadsheets/d/1gIlumW9oaU3uT35Jz4ErqOu7gwYP6miAEGM1h8gXTnM/edit#gid=2018570026

Documento referência
