### ISSUE TITLE
[PAINEL DO ASSOCIADO] Página inicial BOAS VINDAS! 

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#20]
Considerar páginas criadas pelo Paid Memberships Pro

- [x] Criar página inicial do Associado (logado)

layout: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=675-6579&t=BDSOluueRYBCSOgE-0&scaling=min-zoom&page-id=112%3A2

**Comment by everaldomatias** [comment]
Segue para validação a página "Boas vindas" da área do associado. Para validar, acesse `/associados/boas-vindas/`

Itens para fazer:

- [ ] Na versão mobile, o sidebar é colapsado, a equipe de design vai criar o layout dessa parte
- [ ] Os temos **NOME DO GERENTE** e **<empresa>** dependem da definição de como serão estruruados os dados no WordPress/CRM
- [ ] Os links **FALE COM SEU GESTOR DE CONTAS** e **ACESSAR AGENDA** também aguardam definições do fluxo do site

**Comment by daphnemartinsba** [comment]
> 

Criada a issue #50 para essas questões

**Comment by caio-ascava** [comment]
- [ ] Diminuir a fonte de "Banners de Divulgação" e "Fique por dentro do calendário Ethos" para 24px.
- [ ] Aumentar a fonte de "acessar Agenda" no botão para 16px

**Comment by everaldomatias** [comment]
@caio-ascava os ajustes apontados acima foram realizados, pode validar novamente.
