### ISSUE TITLE
[ASSOCIADAS] Elaboração de orientações para a alteração das logos apresentadas via shortcode

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#200]
Na página Nossas Associadas: https://www.ethos.org.br/associados/

As logos apresentadas são exibidas na página através de um shortcode e não podem ser editadas no Wordpress.

- [x] Investigar como alterar as logos
- [ ] Elaborar uma orientação para que a equipe do Ethos ou hacklab/ possa fazer as futuras alterações

A suposição inicial é que elas são integradas com o CRM. O contexto que temos é que essas logos são inseridas no CRM e depois eram enviadas ao WP por meio de outra aplicação, que não conhecemos e não temos documentação.

**Comment by laurahacklab** [comment]
@dioliviers entra nessas ações que o Eve elencou?

**Comment by everaldomatias** [comment]
@dioliviers atuei no código do shortcode e agora conseguimos ocultar os logos.

O que precisamos agora é montar a galeria de logos das empresas associadas, com os mesmos títulos separando as seções. Você pode acessar a lista deles na URL /associados/.

Monta a galeria de logos em uma outra página e quando estiver pronta, copiarmos para a página final e ocultamos mais algum texto, se necessário.

Qualquer dúvida é só chamar,

**Comment by marinarcruz** [comment]
link da nova página: https://dev.ethos.org.br/lista-de-associadas/

validar, fazer search replace dos links para não referenciar o dev. 
Fazer o release.

**Comment by caio-ascava** [comment]
Validação e testes concluídos das orientações de alteração das logos.
