### ISSUE TITLE
[DOWNLOADS] [RECAPTCHA] Adicionar um captcha ao formulário de download de publicação

### ISSUE THREAD

**Issue by marina-hacklab** [Ethos-ti/SiteEthos#205]
No formulário gerado pelo plugin DOIFD para download de arquivos

**Comment by everaldomatias** [comment]
Para adicionar o captcha no formulário de download do plugin DOIFD, foi necessário adicionar nele, dois hooks, são eles:

`doifd_display_recaptcha` e `doifd_registration_form_shortcode`

Para exibição do captcha, utilizamos as mesmas funções do plugin Advanced Google Recatpcha, que já utilizado em outras partes do projeto. E a verificação do preenchimento do captcha acontece na função `get_doifd_form_submit` que está no tema do projeto.

**Comment by caio-ascava** [comment]
Validação foi concluída em 08/11
