### ISSUE TITLE
[SINGLE EVENTOS] Modelo de AGENDA, CURSOS E GRUPO DE TRABALHO

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#21]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2703-21430&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2703-21494&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by marinarcruz** [comment]
Ficará faltando configurar os eventos recorrentes, ação bloqueada pois necessita da versão pro do Events Calendar

**Comment by thiagolamonte** [comment]
Para fazer os testes das possibilidades de agendamentos de eventos é necessário aguradar o Events Calendar Pró. 

link da single - modelo Figma: 

https://ethos.hacklab.com.br/evento/valor-estrategico-ods-e-agenda-2030/

tarefas realizadas:
retirada dos blocos do Events Calendar Free da página de edição. Com o PRÓ vale uma revisão para ver se existem novos blocos 
Formatação da data para modelo brasileiro

**Comment by thiagolamonte** [comment]
Com a utilização do Events Calendar PRO foi refatorado a lógica de exclusão dos blocos para  a retirada do bloco "related-events" . Assim, novos eventos são iniciados sem nenhum bloco no editor e os dados do evento devem ser preenchidos nos metadados. A possibilidade de criar eventos recorrentes, trouxe novos metadados para a sessão cinza claro das singles. Os principais são o "Tipo de Evento" e "Quantidade de eventos". 

Links de teste: 

 https://ethos.hacklab.com.br/evento/encontro-do-grupo-de-trabalho/2024-06-30/
https://ethos.hacklab.com.br/evento/evento-recorrente-semanal/2024-07-02/

**Comment by daphnemartinsba** [comment]
- [ ] Implementar campo de pdf do evento
- [ ] implementar campo de inscrição para todos eventos futuros

**Comment by daphnemartinsba** [comment]
- Definição de metadados referentes aos plugins devem ser desconsiderados na validação dessa issue

**Comment by daphnemartinsba** [comment]
blocked: definição de uso do plugin determinarão de onde vem os metadados, para tanto, precisa determinar o fluxo de evento

**Comment by daphnemartinsba** [comment]
Layout foi implementado, contudo, precisa finalizar os processos de integração com o CRM na issue #133 e #41
