### ISSUE TITLE
[SINGLE PUBLICAÇÕES]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#22]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=365-5685&t=2WiXI7fvmEJetrbd-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-19337&t=2WiXI7fvmEJetrbd-0&scaling=min-zoom&page-id=112%3A2

- [x] metadado de termo (exemplo do layout: direitos humanos)
- [x] thumb, título e resumo
- [x] metadado de data de publicação
- [x] compartilhamento redes sociais 
- [x] card de solicitação de download 

  - disparar email 
  - alerta de campos obrigatórios
  - alerta de checkbox  
- utilizar modelo de envio de formulário: 
https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2188-57861&t=2WiXI7fvmEJetrbd-0&scaling=min-zoom&page-id=112%3A2

- [x] Botão amostra de publicação:
  - ao ser clidado, deve abrir o pdf de amostra da publicação
 
- [x] leia também
- [x] aplicar widget implementado em #14

**Comment by dioliviers** [comment]
Obs: 

inserido reCaptcha que não estava previsto no layout,  e fiz a integração do contact-form no codigo pode ser que haja pontos de ajustes finos por parte do contact form e do reCaptcha, mas de modo geral parece que está similar ao solicitado no layout. 

PS : 
temos vários metadados criados no ACF para a single de publicações, todos são obrigatórios, realmente tem que ser obrigatórios ?

Porque toda single tem um PDF, esse PDF eu sei que tem ligação com o botão " AMOSTRA DA PUBLICAÇÃO" -> já está feito consegui ligar o botão com o metadado 'arquivo_publicacao', para baixar a amostra do conteúdo.
Porém tem um que é 'Documento' ( obrigatório ) que documento ? Todas as singles já vem com o pdf para a amostra mas não vem com o arquivo inserido neste campo.
e tem outro que é "Link para a publicação externa" Obrigatório também ? que link ? Não veio link nenhum nas singles.

Colocando em todo novamente e aguardando retorno dessas questões.

**Comment by daphnemartinsba** [comment]
> Obs:
> 
> inserido reCaptcha que não estava previsto no layout, e fiz a integração do contact-form no codigo pode ser que haja pontos de ajustes finos por parte do contact form e do reCaptcha, mas de modo geral parece que está similar ao solicitado no layout.
> 
> PS : temos vários metadados criados no ACF para a single de publicações, todos são obrigatórios, realmente tem que ser obrigatórios ?
> 
> Porque toda single tem um PDF, esse PDF eu sei que tem ligação com o botão " AMOSTRA DA PUBLICAÇÃO" -> já está feito consegui ligar o botão com o metadado 'arquivo_publicacao', para baixar a amostra do conteúdo. Porém tem um que é 'Documento' ( obrigatório ) que documento ? Todas as singles já vem com o pdf para a amostra mas não vem com o arquivo inserido neste campo. e tem outro que é "Link para a publicação externa" Obrigatório também ? que link ? Não veio link nenhum nas singles.
> 
> Colocando em todo novamente e aguardando retorno dessas questões.

Aguardando retorno sobre os campos
