### ISSUE TITLE
[ASSOCIE-SE] Páginas QUERO ME ASSOCIAR e TERMO DE ASSOCIAÇÃO

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#25]
### QUERO ME ASSOCIAR
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2131-17622&t=at3YK7rzAFd7W9jB-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-17458&t=at3YK7rzAFd7W9jB-0&scaling=min-zoom&page-id=112%3A2

- [x] Box/cards de planos para serem selecionados 
  - Fluxo: o plano deve ser obrigatoriamente selecionado
  - Botão transparente: plano não está selecionado
  - Botão pintado: plano está selecionado
  - APESAR do layout, somente um box pode ser selecionado por vez (caso haja dúvidas, confirme com o designer do projeto)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/7f22ec03-30fd-457c-a169-06dc6698221d)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/d0917b90-c00a-43b6-a19b-ae1cf8335ad8)

- [x] Botão quero me associar direcionará para a página de termos de associação: deve ter um hover explicando que só ficará clicável quando um plano for selecionado

### TERMO DE ASSOCIAÇÃO

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=353-3402&t=at3YK7rzAFd7W9jB-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-17712&t=at3YK7rzAFd7W9jB-0&scaling=min-zoom&page-id=112%3A2

- [ ] Botão aceito os termos de associação leva para a primeira página do formulário de associação

**Comment by barbaburns** [comment]
O fluxo de funcionamento dos botoes dos cards esta complexo, não consigo fazer sozinho. Acho que precisa de javascript aqui.

**Comment by barbaburns** [comment]
A página de termos de associação precisa existir para podermos terminar essa pagina. @leopiccionia ficou responsavel por fazer o javascript para o funcionamento dos botoes do card.

**Comment by barbaburns** [comment]
A Tabela de planos em destaque vira um accordeon em mobile. Quero conversar com @leopiccionia sobre como fazer isso.

**Comment by daphnemartinsba** [comment]
Sugestão do @rafaelchavesfreitas sobre o layout desktop e mobile do QUERO ME ASSOCIAR

- Ocultar a tabela no mobile
- Inserir as informações que estão com os X nos cards de seleção de plano
- Ocultar informações com X dos cards de seleção de plano no desktop

**Comment by barbaburns** [comment]
Layout de pagina esta pronto, faltando o desenvolvimento do javascript pro funcionamento dos botoes.

**Comment by leopiccionia** [comment]
Adicionei os botões.

**Comment by dioliviers** [comment]
Finalizado ajustes com relação ao layout
