### ISSUE TITLE
[FORMULÁRIO DE ASSOCIAÇÃO] DADOS DA EMPRESA e do RESPONSÁVEL: 1° e 2° página

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#26]
Bloqueada: necessita de aprovação do layout
### PRIMEIRA TELA: DADOS DA EMPRESA
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2285-24989&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2285-24879&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

- [x] Só deve ser possível clicar em continuar com o preenchimento de todos os campos obrigatórios e ao marcar o checkbox de termos de uso
- [x] alertas de falta de preenchimento e preenchimento incorreto 

- [x] **Campos obrigatórios**: CNPJ, razão social, seguimentos, faturamento, nome fantasia, quantidade de funcionários e endereço

### SEGUNDA TELA: DADOS DO RESPONSÁVEL
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2285-25052&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2285-24950&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by leopiccionia** [comment]
Falta alguns ajustes apenas, como melhorias de validação e upload de arquivos.

**Comment by daphnemartinsba** [comment]
## 1
- [ ] Retirar obrigatoriedade do campo website e CNAE
- [ ] Inserir as seguintes opções em porte: Grande Empresa, Média Empresa, Pequena Empresa, Micro Empresa
- [ ] Ajustar layout do campo de upload de imagem do iphone 14 max pro


## Cadastro
- [ ] Conta não aprovada consegue fazer login após não ser aprovada

**Comment by daphnemartinsba** [comment]
Formulário 1 - mobile:


https://github.com/Ethos-ti/SiteEthos/assets/75261677/df04c91b-3035-45dd-be3d-77e9e93d8d07

Formulário 1 - desktop:


Formulário 2 - mobile:


https://github.com/Ethos-ti/SiteEthos/assets/75261677/7e1d840d-1c1c-4323-a8f8-42bedcfafba0

Formulário 2 - desktop
