### ISSUE TITLE
[FORMULÁRIO DE ASSOCIAÇÃO] RELAÇÃO e CONTRIBUIÇÃO ASSOCIATIVA: 3° e 4°página

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#27]
Bloqueada: aguardando aprovação final do layout
### RELAÇÃO ASSOCIATIVA

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-17096&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-16633&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

- [x] Plano deve vir previamente selecionado 

- a seleção ocorre na página associe-se

- [x] Plano selecionado deve estar destacado, conforme layout

Demais opções de planos selecionados:
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-17893&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-16788&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-17242&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-16942&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

### CONTRIBUIÇÃO ASSOCIATIVA

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2528-21949&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2528-21871&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by daphnemartinsba** [comment]
Dropdowns contribução associativa:
Faturamento do ano: Micro e pequena (até R$ 16 milhões); Média (R$ 16 milhões a R$ 300 milhões); Grande (maior que R$ 300 milhões) 
Periodicidade do pagamento: Mensal, Semestral, Anual
Condição de pagamento: à vista; Parcelado
Meio de recebimento do termo de associação: E-mail; Correio; Assinatura eletrônica
Meio de recebimento dos boletos: E-mail; Correio
Meio de recebimento dos recibos: E-mail; Correio

**Comment by dioliviers** [comment]
Link para validação do formulário 3 : 
https://ethos.hacklab.com.br/teste-formulario-etapa3/

**Comment by daphnemartinsba** [comment]
Layout change: mobile

- Ocultar a tabela no mobile
- Inserir as informações que estão com os X nos cards de seleção de plano
- Ocultar informações com X dos cards de seleção de plano no desktop

**Comment by caio-ascava** [comment]
No formulário da etapa 3, 4 e 5 há a descrição: "Campos marcados com * são obrigatórios", mas nestas partes não há campos obrigatórios

- [ ] descrição diferente
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/5e9605df-7eec-4b9d-bd97-8c98f671fbed)

- [ ] descrição diferente
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/f21cbf34-4e3b-47a5-afe6-8090936a57f5)

**Comment by dioliviers** [comment]
Resolvido. Se colocar na listagem o texto riscado automáticamente o interpretador vê como um uncheck X e insere no mobile
