### ISSUE TITLE
[FORMULÁRIO DE ASSOCIAÇÃO] INFORMAÇÕES ADICIONAIS: 5° página

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#28]
- [ ] UI/UX: ajustar tela de inserção de dados do contato

- [ ] Ao clicar em enviar formulário deve abrir a confirmação de envio
Layout modal envio desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2285-25642&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by daphnemartinsba** [comment]
bloqueio: uso do plugin paid membership pro

**Comment by caio-ascava** [comment]
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/45d4d27d-3d45-4651-b904-086cb8a02791)
