### ISSUE TITLE
[ASSOCIADO] LOGIN e RECUPERAÇÃO DE SENHA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#30]
### LOGIN - https://ethos.hacklab.com.br/wp-login
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2514-20584&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2514-20554&t=AQT5y6DeQN7WV6uS-0&scaling=min-zoom&page-id=2280%3A15317

- O login do usuário utilizará o plugin paid membership

### RECUPERAÇÃO DE SENHA - https://ethos.hacklab.com.br/login/?action=reset_pass

- [ ]  Layout a definir, se será com base na identidade visual ou pelo plugin paid membership

**Comment by marinarcruz** [comment]
24/05: Serão as telas padrão do WP. Estilizar de acordo com a componetização. Consultar Eve/Ester se precisar entender mais sobre.

**Comment by marinarcruz** [comment]
pareando com Julia
