### ISSUE TITLE
[PAINEL DO ASSOCIADO] PERFIL DA EMPRESA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#31]
### TAREFA GERAL
- A página possui três abas:
  - Dados da empresa
  - Contatos
  - Financeiro 
- [x] Essa seção do painel do associado deve ficar disponível somente para usuários com permissão de administrador no paid membership pro

### DADOS DA EMPRESA
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-20360&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21342&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317

- [x] Botão editar deve tornar a edição dos campos disponível
- [x] Quando a edição do campo estiver disponível, alterar nome do botão para salvar
- [x] Ao clicar em salvar os dados devem ser salvos nos campos

### CONTATOS
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-20424&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21393&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317

- [x] Ao adicionar um contato, deve abrir a modal de dados do contato
- [x] Implementar modal de dados do contato: utilizada/desenvolvida na issue #28 

- [ ] Implementar busca 
- [ ] Implementar filtros da busca
- [x] Componente de paginação

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2285-25862&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317

### FINANCEIRO
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2782-22040&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2782-22226&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317

- [x] Botão editar deve tornar a edição dos campos disponível
- [x] Quando a edição do campo estiver disponível, alterar nome do botão para salvar
- [x] Ao clicar em salvar os dados devem ser salvos nos campos

**Comment by daphnemartinsba** [comment]
bloqueio: uso do plugin paid membership pro

**Comment by dioliviers** [comment]
aba de financeiro finalizada, pendente a aba de contatos ( beckend ).

**Comment by daphnemartinsba** [comment]
- Coluna membros sera descontinuada

**Comment by dioliviers** [comment]
Obs: conforme informação do léo em CONTATOS não haverá campo de buscas.
