### ISSUE TITLE
[PAINEL DO ASSOCIADO] MEUS DADOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#32]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-20484&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21440&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by daphnemartinsba** [comment]
bloqueio: uso do plugin paid membership pro

**Comment by marinarcruz** [comment]
Formulário não está salvando os dados

**Comment by caio-ascava** [comment]
- [ ]  Realizar tradução do botão "Salvar Alterações" e inverter cores.

![Image](https://github.com/user-attachments/assets/f60416f8-42dd-4a1b-b878-953a16d3583c)
