### ISSUE TITLE
[PAINEL DO ASSOCIADO] MEU PLANO

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#33]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-20734&t=kuHCYVdM4JGXeRhk-0&scaling=min-zoom&page-id=2280%3A15317
https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-20515&t=kuHCYVdM4JGXeRhk-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21121&t=kuHCYVdM4JGXeRhk-0&scaling=min-zoom&page-id=2280%3A15317
https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21134&t=kuHCYVdM4JGXeRhk-0&scaling=min-zoom&page-id=2280%3A15317

- [x] Deve exibir o plano da empresa associada
- [x] Ao clicar em: Para mais informações sobre os planos de associação, clique aqui deve direcionar para a página de solicitações com a opção de cancelar inscrição pré selecionada no checkbox
- [x] Ao clicar em Solicitar mudança de plano direciona para página de Solicitações

**Comment by daphnemartinsba** [comment]
bloqueio: uso do plugin paid membership pro

**Comment by caio-ascava** [comment]
- [ ] em mobile, o layout está quebrando. 
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/0b3e7b5a-aabc-477d-bb5a-ba3636aba541)

**Comment by caio-ascava** [comment]
Em desktop está tudo conforme.

Em Mobile:
Na resolução de 360 x 3739 o bloco com a descrição do plano, o botão de "solicitar mudança de Plano" e a tabela ficam quebradas. E o scroll para o lado direito não é possível. 
![Image](https://github.com/user-attachments/assets/cfb78f03-604a-483a-a147-21b84d60554f)

A resolução mínima para que os blocos apareçam é: 482 (width), porem o botão de "solicitar mudança de Plano" não centraliza em mobile.
![Image](https://github.com/user-attachments/assets/485be4a2-76a8-4e4d-86a7-b21324035366)
