### ISSUE TITLE
[PALESTRAS]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#34]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=316-3136&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-19861&t=18JtZVyhbNwZGYuO-0&scaling=min-zoom&page-id=112%3A2

**Comment by barbaburns** [comment]
O bloco de acordeon não aceita icones no titulo. Preciso ver com @leopiccionia  ou @rafaelchavesfreitas qual melhor caminho seguir nesse caso.

**Comment by daphnemartinsba** [comment]
blocked: precisa de orientação para finalizá-la

**Comment by barbaburns** [comment]
é preciso gerar um icone para a aba Outros no mesmo formato dos outros icones.

**Comment by caio-ascava** [comment]
- [ ] Incluir o Recaptcha, antes do botão de "Enviar Formulário"
- [ ] Incluir mensagem de campo obrigatório
- [ ] As flechas da tabela de "Temas" e "Considerações da realização" são em negrito BOLD
- [ ] Verificar o ícone do formulário de Solicitação de Palestra que não carrega.

Estes ajustes citados acima são necessários tanto em Desktop quanto via Mobile

**Comment by barbaburns** [comment]
ícone do formulário de Solicitação de Palestra carrega normalmente tanto em dev quanto no meu local.


![Image](https://github.com/Ethos-ti/SiteEthos/assets/11669690/abc0f10a-9940-401a-adaf-473148c6be8a)
