### ISSUE TITLE
[RESULTADOS DE BUSCA] BUSCA & BUSCA VAZIA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#35]
### BUSCA
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2836-63905&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2836-64242&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=112%3A2

### BUSCA VAZIA

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=3339-15431&t=wOJNvWl8lN4GwBMQ-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=3339-15370&t=wOJNvWl8lN4GwBMQ-0&scaling=min-zoom&page-id=112%3A2

**Comment by thiagolamonte** [comment]
nos testes finais foi detectado que como os eventos não compartilham as mesmas categorias dos demais cpts, as abas das caterorias direitos humanos, integridade e etc, não funcionavam como esperado quando a busca era filtrada no select pro eventos. 

Decidi tirar momentaneamente o filtro por eventos para poder manda a issue para validação.

**Comment by daphnemartinsba** [comment]
> blocked: confirmando arquitetura de eventos

Eventos terão categorias. Categorias estão sendo criadas

**Comment by daphnemartinsba** [comment]
Eventos serão listados na issue #60

**Comment by thiagolamonte** [comment]
a pagina foi criada se baseando no layout do figma o que inclui o layout dos cards e do grid de posts
