### ISSUE TITLE
[PAINEL DO ASSOCIADO] CONTEÚDOS SELECIONADOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#37]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-20912&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21154&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317

- [ ] Filtros de exibição por CPT
- [ ] Filtros de áreas do atuação do ethos
- [x] grid
- [ ] componente de paginação
- [x] Conteúdos que serão produzidos pensando nos associados, serão públicos
- [ ] O conteúdo exibido será marcado com um campo do pods e uma taxonomia

**Comment by daphnemartinsba** [comment]
- Filtros não serão implementados
- Paginação deve levar para uma archive dos conteúdos selecionados

**Comment by dioliviers** [comment]
Conforme acordado na Semanal, não haverá no momento filtro nem accordeon. 

Em vez da paginação ( como não é uma arquive ) como medida paliativa foi inserido um botão " Ver mais " para redirecionamento.
