### ISSUE TITLE
[PAINEL DO ASSOCIADO] Visualização dos status das INSCRIÇÕES

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#38]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2643-29053&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2643-29113&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317

- A inscrição necessita de duas aprovações, primeiro a do perfil aprovador, do cadastro e depois do ethos
- As inscrições ocorrem em eventos, cursos, grupos de trabalho

- [ ] Status Em análise: quando o usuário deve ser aprovado pelo ethos (Caminho CRM - Inscrição Dados Financeiros - Filtro em Análise)
- [ ] Status Disponível: quando a inscrição já foi aprovada pelo Ethos (Caminho CRM - Inscrição Dados Financeiros - Filtro Disponível)
- [ ] Status Cancelada: quando a inscrição foi cancelada pelo Ethos (Caminho CRM - Inscrição Dados Financeiros - Filtro Cancelada)

- [ ] Cada usuário deve ver somente sua inscrição
- [ ] Administrador pode ver todas

**Comment by daphnemartinsba** [comment]
blocked: issue #41 e issue #42

**Comment by filipesouzadev** [comment]
Aguardando os dados do CRM para concluir a parte dinâmica dos dados no bloco.

**Comment by daphnemartinsba** [comment]
blocked: depende da integração do CRM, layout feito, precisa dos dados

**Comment by daphnemartinsba** [comment]
- [ ] Cada usuário deve ver somente sua inscrição
- [ ] Administrador pode ver todas

**Comment by marinarcruz** [comment]
bloqueada: precisa de apoio do Leo para poder importar os dados do CRM para testar em ambiente local. A página foi alterada para ser somente uma exibição dos dados do CRM.

**Comment by leopiccionia** [comment]
Atualmente usamos o texto dos status que vêm diretamente do CRM. No CRM, há cerca de 20 status possíveis.

**Comment by filipesouzadev** [comment]
link para validação:

https://ethos.hacklab.com.br/associados/inscricoes/

**Comment by marinarcruz** [comment]
06/08: Precisa ajustar os erros que aparecem, como no abaixo:
