### ISSUE TITLE
[PAINEL DO ASSOCIADO] SOLICITAÇÕES

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#39]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21562&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21255&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by dioliviers** [comment]
OBS: fico pendente a questão do campo do horário, por gentileza equipe, verificar se realmente é necessário esse campo do horário, caso seja, verificar se é plausível inserir o horário no mesmo campo da data por exemplo : 14/06/2024 15:35 em vez de 
Data: 
14/06/2024
Horário:
15:35

**Comment by dioliviers** [comment]
Bloqueio por questão das horas a serem apresentadas no contactform, onde na documentação não achei suporte, achei apenas para Data, Mês e Ano.

**Comment by daphnemartinsba** [comment]
desbloqueado com o uso de plugin
Falta: alterar texto de CAMPO NÃO PREENCHIDO + debug de campos obrigatórios

**Comment by thiagolamonte** [comment]
https://ethos.hacklab.com.br/associados/minhas-solicitacoes/

foi necessário alterar a estrutura dos campos por dentro do contact form 7 para conseguir a obrigatoriedade dos campos, com isso os Placeholders dos inputs tiveram que ser alterados, mantendo o placeholder padrão da tag <select> e do campo de data

**Comment by daphnemartinsba** [comment]
Layout de solicitações foi aplicado respeitando o padrão dos selects e do formulário do contact form 7


email disparado com o clique no botão enviar solicitação:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/fae5ec22-786c-4627-99b3-57ecb81df886)

desktop:

https://github.com/Ethos-ti/SiteEthos/assets/75261677/3be232bd-404c-451d-b74c-c187e0058a2f


mobile:


https://github.com/Ethos-ti/SiteEthos/assets/75261677/b3df533e-cbac-4d20-ae98-5640d380c5ed
