### ISSUE TITLE
[PAINEL DO ASSOCIADO] PAGAMENTO e FATURA DIGITAL

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#40]
### PAGAMENTO
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=4170-33861&t=8xk9NwKN4cDdqsYj-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21462&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317

### FATURA DIGITAL
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=4170-34780&t=8xk9NwKN4cDdqsYj-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2284-21531&t=DBZy0hcb4RQUreIJ-0&scaling=min-zoom&page-id=2280%3A15317

**Comment by daphnemartinsba** [comment]
blocked: 
Pagamento: integração CRM
Fatura digital: dado de boleto

**Comment by daphnemartinsba** [comment]
**Retirar botão de pagar boleto nas duas telas**

**Comment by filipesouzadev** [comment]
Aguardando os dados do CRM para concluir a parte dinâmica dos dados no bloco.

**Comment by daphnemartinsba** [comment]
blocked: depende da integração do CRM

**Comment by marinarcruz** [comment]
Foi excluída a tela de Fatura Digital - não implementar.
Os campos a serem exibidos, com a devida integração ao CRM são:

Data da emissão do recibo = data de início do contrato
ID - Código financeiro (Fica em contas->resumo)
Valor 
Periodicidade (Mensal, Anual, etc)
Status: Adimplente ou Inadimplente (Contatos - Situação)

**Comment by daphnemartinsba** [comment]
Layout:
https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=4170-33861&t=LxeGj1T9Lb88T8DO-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2
Parcerias. Campos:

- [ ] Início da vigência - data de início

- [ ] Projeto

- [ ] Periodicidade

- [ ] Valor

- [ ] Situação
