### ISSUE TITLE
[INTEGRAÇÃO CRM] INSCRIÇÃO EM EVENTOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#41]
Fluxo atual: a inscrição em evento é criada pelo CRM, isso gera um link que ao ser colado na single gera o formulário de inscrição
- [ ] Implementar a inscrição em eventos: CRM -> WP

- [ ] Pararemos de usar o events ticket para pagamentos, avaliar se usaremos o RSVP

- [ ] Implementar/integrar certificados
- [ ] Implementar/integrar vouchers
- [ ] implementar/integrar cortesias

**Comment by marinarcruz** [comment]
Provavelmente será substituída pelo plugin de eventos

**Comment by daphnemartinsba** [comment]
Blocked: definir fluxo de eventos: criação da inscrição pelo CRM

**Comment by marinarcruz** [comment]
Tipos de eventos mapeados pela @estercmandrade 

 exemplificação por tipo de evento, no sandbox e produção:
Conferência Ethos

Link sandbox:
- Exemplo futuro/atual: Não está no sandbox por estar em prod
- Exemplo passado: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&forceUCI=1&pagetype=entityrecord&etn=fut_projeto&id=f8e03df2-2990-ed11-aad1-00224836ddc6
link inscrição:
- Exemplo futuro/atual: https://www.ethos.org.br/conteudo/inscricao-conferencia?id=1355
- Exemplo passado: https://www.ethos.org.br/conteudo/inscricao-conferencia?id=1241
link imprensa:
- Exemplo futuro/atual: https://www.ethos.org.br/conteudo/inscricao-conferencia?id=1355&imp=1235922
- Exemplo passado: https://www.ethos.org.br/conteudo/inscricao-conferencia?id=1241&imp=1235808
link certificado:
- Exemplo futuro/atual: https://www.ethos.org.br/conteudo/certificado-conferencia?id=1355
- Exemplo passado: https://www.ethos.org.br/conteudo/certificado-conferencia?id=1241
link cortesia:
- Exemplo futuro/atual: https://www.ethos.org.br/conteudo/inscricao-conferencia?id=1355&cts=1235922
- Exemplo passado: https://www.ethos.org.br/conteudo/inscricao-conferencia?id=1241&cts=1235808

Conversas com lideranças (exemplos não pagos)

Link sandbox:
- Exemplo passado: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&forceUCI=1&pagetype=entityrecord&etn=fut_projeto&id=055bce7f-10b6-ed11-b596-002248e0d6a7
Link site:
- Exemplo passado: https://www.ethos.org.br/conteudo/inscricao-evento?id=1248
- Exemplo futuro/atual: https://www.ethos.org.br/conteudo/inscricao-evento/?id=1375

Conexão Ethos

Link sandbox:
- Exemplo passado: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&pagetype=entityrecord&etn=fut_projeto&id=2a08c13a-455a-e911-a953-000d3ac03470
link site:
- Exemplo passado: https://www.ethos.org.br/cedoc/conexoes-ethos-curitiba/

Grupo de trabalho e Cursos também são projetos do tipo evento, e o tipo de evento é evento mesmo. Vou pegar exemplos também. Falta mapear:
Ethos Serviços
Palestras
Rodas de Diálogo

**Comment by daphnemartinsba** [comment]
Projeto do tipo evento com tipo de evento sendo evento: 

- Conversa com lideranças: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&forceUCI=1&pagetype=entityrecord&etn=fut_projeto&id=055bce7f-10b6-ed11-b596-002248e0d6a7
- Conexão ethos: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&pagetype=entityrecord&etn=fut_projeto&id=2a08c13a-455a-e911-a953-000d3ac03470
- Grupo de trabalho: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&pagetype=entityrecord&etn=fut_projeto&id=af9b9852-3511-ee11-8f6e-000d3ac161d0
- Roda de diálogo: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&pagetype=entityrecord&etn=fut_projeto&id=d8370429-4073-e811-8142-70106fa70181

Projeto do tipo conferência:

- Conferência: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&forceUCI=1&pagetype=entityrecord&etn=fut_projeto&id=f8e03df2-2990-ed11-aad1-00224836ddc6

Projeto do tipo curso:

- Curso: https://ethossandbox.crm2.dynamics.com/main.aspx?appid=554bbd88-6076-ea11-a811-000d3ac18841&pagetype=entityrecord&etn=fut_projeto&id=9aebd64a-b87c-ed11-81ad-000d3a89219b

**Comment by marinarcruz** [comment]
25/07 - Foi realizado um teste de inscrição em eventos por parte de uma pessoa logada e foi feito com sucesso.
Precisamos fazer o fluxo da inscrição em eventos para pessoas não logadas - os dados são coletados pelo CRM e cria-se um cadastro (?) - investigar a integração desses dados com o CRM. Descobrir o objeto que cria a entidade usuário. Usuário no CRM é a entidade Contact. Para criar uma fut_participante, precisamos passar o ID do projeto (evento) e o ID da pessoa. Se ela não está logada, ela não tem o ID ainda. Precisaremos descobrir se tem outra entidade que pode ser criada de maneira mais simples para gerar esse ID sem precisar estar logada.

**Comment by marinarcruz** [comment]
Precisamos fazer a distinção entre evento exclusivo ou não, para que seja enviado ao WP nessa condição

**Comment by marinarcruz** [comment]
02/08: Rafa fazendo a integração do plugin antigo do processo de criação do evento no CRM e atualização automática no WP.
Pretende puxar mais eventos a cada hora.
Precisamos combinar a migração dos eventos no novo.ethos
Precisamos estudar a integração do CRM com o plugin events calendar no novo.ethos para fazer funcionar o bloco da home e nas singles.
