### ISSUE TITLE
[INTEGRAÇÃO COM CRM] Criação de evento do CRM para o WP

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#42]
- [x] Atualização dos dados: WP <-> CRM
- [x] Criação dos eventos: CRM -> WP

**Comment by daphnemartinsba** [comment]
Sem acesso ao CRM. Precisa recuperar senha

**Comment by marinarcruz** [comment]
Verificar como é feita a inscrição dos eventos, com aprovação, pagamento e vouchers.
PMPro tem códigos de desconto, tem compra por grupo, tem possibilidade de ter valores diferentes para diferentes atores.
Ponto de atenção: Eventos pagos, checar se tem na versão do Events Calendar. Entender direito e ver se estamos cobertos.

**Comment by daphnemartinsba** [comment]
### Edição dos dados: 

- precisa criar estratégia para que os dados sejam atualizados do CRM para o WP, no momento são feitos de forma pontual pelo script
- do WP para o CRM é possível adaptar o script de enviar dados para que atualize os dados
- informação importante: comparar datas de última edição, tem tanto no WP quanto no CRM, para garantir que mantenha coerência. Exemplo: se no WP foi editado num dia 10, e no CRM no dia 15, ao acessar o WP após o dia 15, o WP tem que conter a atualização do CRM

**Comment by daphnemartinsba** [comment]
Será atualizada somente do WordPress para CRM

**Comment by daphnemartinsba** [comment]
- Evento é criado do CRM para o WP com o intervalo aproximado de 1 em 1 hora
- metadado de data é puxado 
- conteúdo textual do campo do CRM Condições (Política) do Evento - Preâmbulo, Corpo, Corpo Padrão e/ou Cortesia e Complemento aparentemente não é puxado

**Comment by daphnemartinsba** [comment]
criada issue #133 para resolver os retornos
