### ISSUE TITLE
[DOCUMENTAÇÃO] Usuário

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#44]
- [ ] Utilizar modelo de página âncora
- [ ] Inserir informação sobre dimensões de imagens: 
  - Logo cabeçalho: 150x150 

- [ ] Para postagem aparecer em conteúdos exclusivos, na área de associados, tem que ter a categoria curadoria marcada

**Comment by caio-ascava** [comment]
aguardando a definição dos fluxos dos eventos.

**Comment by daphnemartinsba** [comment]
- [ ] Verificar links criados a partir da criação do projeto no CRM
  - Link de Inscrição
  - Link de Certificado
  - Link de Cortesia
  - Link de Imprensa
- [ ] Finalização do evento e disparo de email de certificado

**Comment by daphnemartinsba** [comment]
caso de teste: quando a inscrição é realizada pelo CRM não há disparo de email com o link do certificado

**Comment by daphnemartinsba** [comment]
- Palestras: cria evento no wordpress e coloca link no zoom (não tem ligação com o CRM). Obs: só a solicitação de palestra tem ligação com o CRM

**Comment by estercmandrade** [comment]
- [ ] Verificar se os metadados Centro de Mídia, Conteúdos Relacionados, Parceiros, Relacionamento estão sendo utilizados


- [ ] Remover da documentação e painel caso não estejam
