### ISSUE TITLE
[CABEÇALHO] ACESSIBILIDADE

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#46]
- [ ] @marina-hacklab Encontrar plugin de acessibilidade (contrate, aumento e diminuição da fonte) que se assemelhe ao layout
- utilizado no NINJA: WP Acessibility https://br.wordpress.org/plugins/wp-accessibility/
- [ ] @barbaburns Ícones de acessibilidade: ajustar os ícones do lado direito (com destaque ao A+ e A- que são com flechas), conforme Figma eles são maiores e suas bordas mais finas

**Comment by barbaburns** [comment]
em conversa com o @leopiccionia ele acredita que vamos precisar desenvolver nosso proprio plugin de acessibilidade.

**Comment by daphnemartinsba** [comment]
- [ ]  Investigar plugins de acessibilidade

- elaboração de plugin pelo tema base: 2 dias

**Comment by marinarcruz** [comment]
Precisa de investigação maior sobre quais são os plugins que usaremos como padrão para os itens de acessibilidade que estão previstos no contrato. @rafaelchavesfreitas orientar a pesquisa para que a @marina-hacklab faça a análise e depois a gente defina como seguir.

**Comment by marinarcruz** [comment]
Análise feita com @rafaelchavesfreitas em 21/06:
Plugins que podemos instalar de antemão:
- VLibras
- Text to Speech - precisamos analisar a quantidade de CPTs se atende a todos do projeto. Se não atender, precisaria ser a versão Pro.
- Aumento e diminuição de fonte: desenvolver internamente e aplicar a partir do tema-base
- Contraste: desenvolver internamente e aplicar a partir do tema-base

**Comment by marina-hacklab** [comment]
Sobre o plugin Text to Speech:

De acordo com as características da apresentação do plugin no link

https://wordpress.org/plugins/text-to-audio/

Ele apresenta na versão gratuita o suporte a CPTs ilimitados e compatibilidade dos plugins que criam os CPTs, como o ACF e afins.

"Custom Post Type Compatibility: Extend text to voice functionality to custom post types, ensuring consistency across your entire website. Integrate with popular custom post type plugins such as [Advanced Custom Fields (ACF)](https://wordpress.org/plugins/advanced-custom-fields/), [Custom Post Type UI](https://wordpress.org/plugins/custom-post-type-ui/)
, and [Toolset Types](https://toolset.com/home/types-manage-post-types-taxonomy-and-custom-fields/)."

A versão Pro apresenta mais recursos avançados para a seleção fina de conteúdos a serem lidos, vozes utilizadas, além de Downloads ilimitados dos áudios: https://atlasaidev.com/plugins/text-to-speech-pro/

Diagnóstico: em tese a versão gratuita cumpre os requisitos necessários para a utilização com inúmeros CPTs e aceita quaisquer modificações no layout via CSS que forem necessárias.

**Comment by marina-hacklab** [comment]
Quanto às alterações de acessibilidade no texto para o desenvolvimento:

De acordo com a documentação Web Content Accessibility Guidelines (WCAG) 2.0 (Diretrizes de acessibilidade de conteúdo web):

https://www.w3.org/Translations/WCAG20-pt-br/#visual-audio-contrast

Na Diretriz 1.4 encontramos as orientações minimas e as ideais para serem aplicadas.

"1.4.3 Contraste (Mínimo): A apresentação visual de [texto](https://www.w3.org/Translations/WCAG20-pt-br/#textdef) e [imagens de texto](https://www.w3.org/Translations/WCAG20-pt-br/#images-of-textdef) tem uma [relação de contraste](https://www.w3.org/Translations/WCAG20-pt-br/#contrast-ratiodef) de, no mínimo, 4.5:1, exceto para o seguinte: (Nível AA)

    Texto Ampliado: Texto em [tamanho grande ](https://www.w3.org/Translations/WCAG20-pt-br/#larger-scaledef)e as imagens compostas por texto em tamanho grande têm uma relação de contraste de, no mínimo, 3:1;

    Texto em plano Secundário: O texto ou imagens de texto que fazem parte de um [componente de interface de usuário ](https://www.w3.org/Translations/WCAG20-pt-br/#user-interface-componentdef)inativo, que são [meramente decorativos](https://www.w3.org/Translations/WCAG20-pt-br/#puredecdef), que não estão visíveis para ninguém, ou que são parte de uma imagem que inclui outro conteúdo visual significativo, não têm requisito de contraste.

    Logotipos: O texto que faz parte de um logotipo ou marca comercial não tem requisito de contraste."
    
"1.4.4 Redimensionar texto: Exceto para [legendas](https://www.w3.org/Translations/WCAG20-pt-br/#captionsdef) e [imagens de texto](https://www.w3.org/Translations/WCAG20-pt-br/#images-of-textdef), o [texto](https://www.w3.org/Translations/WCAG20-pt-br/#textdef) pode ser redimensionado sem [tecnologia assistiva](https://www.w3.org/Translations/WCAG20-pt-br/#atdef) até 200 por cento sem perder conteúdo ou funcionalidade. (Nível AA)"

"1.4.6 Contraste (Melhorado): A apresentação visual do [texto](https://www.w3.org/Translations/WCAG20-pt-br/#textdef) e [imagens de texto](https://www.w3.org/Translations/WCAG20-pt-br/#images-of-textdef) tem uma [relação de contraste](https://www.w3.org/Translations/WCAG20-pt-br/#contrast-ratiodef) de, no mínimo, 7:1, exceto para as seguintes situações: (Nível AAA)

    Texto Ampliado: Texto [em tamanho grande](https://www.w3.org/Translations/WCAG20-pt-br/#larger-scaledef) e as imagens compostas por texto em tamanho grande têm uma relação de contraste de, no mínimo, 4.5:1;

    Texto em plano Secundário: O texto ou as imagens de texto que fazem parte de um [componente de interface de usuário](https://www.w3.org/Translations/WCAG20-pt-br/#user-interface-componentdef) inativo, que são [meramente decorativos](https://www.w3.org/Translations/WCAG20-pt-br/#puredecdef), que não estão visíveis para ninguém, ou que fazem parte de uma imagem que inclui outro conteúdo visual significativo, não têm requisito de contraste.

    Logotipos: O texto que faz parte de um logotipo ou marca comercial não tem requisito de contraste mínimo."

"1.4.8 Apresentação Visual: Para a apresentação visual de [blocos de texto](https://www.w3.org/Translations/WCAG20-pt-br/#blockstextdef), um [mecanismo](https://www.w3.org/Translations/WCAG20-pt-br/#mechanismdef) está disponível para se obter o seguinte: (Nível AAA)

    As cores do primeiro plano e do plano de fundo podem ser selecionadas pelo usuário.

    A largura não tem mais do que 80 caracteres ou glifos (40 se CJK).

    O texto não é justificado (alinhado a ambas as margens esquerda e direita).

    O espaçamento entre linhas (principal) tem, no mínimo, um espaço e meio nos parágrafos, e o espaçamento entre parágrafos é, no mínimo, 1,5 vezes maior do que o espaçamento entre linhas.

    O texto pode ser redimensionado sem tecnologia assistiva até 200 por cento, de um modo que o usuário não necessite rolar horizontalmente para ler uma linha de texto [em uma janela em tela cheia](https://www.w3.org/Translations/WCAG20-pt-br/#fullscreenwindowdef)."

**Comment by barbaburns** [comment]
Sobre o plugin Text to Speech:

A versão gratuita só permite "ouvir" uma pagina ou post/cpt por vez. Será necessário a versão paga. Testei usando post e pagina. Na home achei bem confuso pq o plugin não segue a segmentação do conteudo. 

Sobre o plugin VLibras: 

Plugin parece estar abandonado, não recebe atualização a 4 anos. Testei e funciona medio, alguns verbos não tem concordancia e tb falta pontuação no texto. Eu não tenho conhecimento de libras, não sei se é uma questão da tradução que se perde mesmo ou se é falha do plugin.

**Comment by leopiccionia** [comment]
Sobre o VLibras, minha experiência em outros sites me leva a crer que é só uma diferença na sintaxe entre a língua portuguesa e Libras, mesmo.

**Comment by marina-hacklab** [comment]
> Sobre o VLibras, minha experiência em outros sites me leva a crer que é só uma diferença na sintaxe entre a língua portuguesa e Libras, mesmo.

Sim, Libras não faz concordância de gênero e número na maior parte das situações que o português faria, então é esperada uma diferença nesse sentido.

**Comment by barbaburns** [comment]
Sobre tamanho de fonte de contraste: 

O Wp Accessibility ja esta foi instalado e ele fica com os icones a esquerda, podem ser customizados para melhorar o layout.

![Image](https://github.com/user-attachments/assets/1d97964c-7d88-404c-8914-57840cc0b119)

O UserWay é mais discreto e tem mais opções de uso.


![Image](https://github.com/user-attachments/assets/38ebeec7-7705-44f2-af24-1ae248612db0)

**Comment by marina-hacklab** [comment]
Todos os recursos do VLibras e UserWay estão funcionando como previsto.
