### ISSUE TITLE
[AGENDA] CABEÇALHOS de GRUPO DE TRABALHO e CURSOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#47]
As archives de Grupo de Trabalho e Cursos estão utilizando o plugin events calendar

- [x] Investigar/implementar cabeçalho das archives de acordo com o estilo previsto para agenda. Com o título Grupo de Trabalho e Cursos

https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=365-5146&t=wN2mf14dgwXfWwAr-0&scaling=min-zoom&page-id=112%3A2

**Comment by thiagolamonte** [comment]
https://ethos.hacklab.com.br/agenda/category/grupos-de-trabalhos/


https://ethos.hacklab.com.br/agenda/category/cursos/
