### ISSUE TITLE
[SINGLE POST] Corrigir subtítulo e imagem duplicada (destaque)

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#49]
- [x] Remover categoria +" _" do subtítulo (resumo). 

Ex: ETHOS DIREITOS HUMANOS_Desinfecção da água para consumo humano é principal orientação
Correto: Desinfecção da água para consumo humano é principal orientação
https://ethos.hacklab.com.br/medicos-listam-recomendacoes-para-evitar-doencas-em-meio-a-enchentes/

Ex: ETHOS MEIO AMBIENTE_Taxação pode garantir US$ 900 bi até 2030, diz relatório; além de fundo para países em desenvolvimento, comunidades vulneráveis nos países ricos também seriam contempladas
Correto: Taxação pode garantir US$ 900 bi até 2030, diz relatório; além de fundo para países em desenvolvimento, comunidades vulneráveis nos países ricos também seriam contempladas
https://ethos.hacklab.com.br/imposto-sobre-petroleo-pode-impulsionar-financiamento-climatico-para-paises-pobres/

- [ ] Remover subtítulo (resumo) e imagem da capa ( imagem destacada) do corpo da publicação.
https://ethos.hacklab.com.br/instituto-ethos-divulga-iniciativas-de-doacoes-humanitarias-em-meio-a-emergencia-no-rs/

Script foi feito no projeto RBA e Mídia.NINJA

Referência:
https://gitlab.com/redebrasilatual/rba-site/-/commits/bugfix/duplicated-images

https://github.com/midianinja/ninja-wp-theme/issues/78

**Comment by marinarcruz** [comment]
Checado o link https://ethos.hacklab.com.br/instituto-ethos-divulga-iniciativas-de-doacoes-humanitarias-em-meio-a-emergencia-no-rs/, em dev, não consta a duplicação. É preciso rodar o script que corrigiu em prod, pois ainda consta com dados duplicados: https://www.ethos.org.br/instituto-ethos-divulga-iniciativas-de-doacoes-humanitarias-em-meio-a-emergencia-no-rs/

**Comment by everaldomatias** [comment]
Em testes locais funcionou e usando o script em um post específico, também funcionou. Para rodar em todos os posts de produção, precisa apagar a option `remove-thumbnail-and-excerpt-option`.

FYI @jacsonp @marinarcruz
