### ISSUE TITLE
[PLUGIN] Avaliar plugin de integração com CRM Ethos Associados

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#5]
- [x] Avaliar quais dados estão integrados com CRM através do plugin Ethos Associados

- [x] Avaliar se é melhor aproveitar o plugin e fazer as melhorias ou se é melhor criar outro plugin de integração com base nas novas informações que estão no layout. É importante lembrar que a Associação será feita através do plugin PaidMembership Pro e Woocommerce.

**Comment by marinarcruz** [comment]
04/06 - solução: desenvolver na unha, fazer as telas iniciais via javascript e depois manter os padrões do plugin Paid Membership Pro.

**Comment by everaldomatias** [comment]
Na avaliação do plugin Ethos Associados, listei as funções que julguei mais relevantes para nos dar um entendimento das regras de negócio, são elas:

**itfService**

**auxGerascriptSimples**

**saveCiaAux**

**buscaCiaAux**

**dadosAssociado**

**areaAssociado**

**listaRequisicoesAcesso**

**dadosSignatario**

**getRefPagSeguro**

**geraCertificado**

**exibirListaEventos**

**solicitarInscricao**

**auxExibePagamentos**

**usoFeitoPelaAssociada**

**auxPreencheXML**

**auxAjaxSolicitaPalestra**

Essas são funções que se conectam ao CRM e/ou criam formulários que enviam e-mails para o Ethos.

O plugin Ethos Associados também cria tabelas personalizadas no banco de dados (mas fora do prefixo wp_), são elas:

- eth_associados
- eth_eventos
- eth_grupos_trabalho
- eth_inscricoes
- eth_patrocinios
- eth_users


- Na pesquisa dos plugins **Dynamics 365 Integration** e **Integrate Dynamics 365 CRM**, a primeira opção me pareceu mais flexível na questão de documentação, filtros e hooks (não identifiquei dentro do plugin, pelo menos na versão free, nenhuma criação de API no WordPress).

Esses são pontos relevantes sobre os dois:

**Dynamics 365 Integration**

https://br.wordpress.org/plugins/integration-dynamics/

- Suporte ao Dynamics 365 Online, Dynamics 365 On-Premises e Dynamics CRM 2011, 2013, 2015 e 2016.
- Criação de formulários no Dynamics 365/CRM e inserção no site com shortcode.
- Escrita de dados dos formulários diretamente no Dynamics 365/CRM.
- Coleta de leads, solicitações de contato, consultas de suporte e muito mais sem necessidade de codificação.
- Exibição de registros usando visualizações do Dynamics 365/CRM com shortcode.
- Vinculação de posts e páginas do WordPress aos registros do Dynamics 365/CRM.
- Suporte para imagens de entidades e imagens anexadas com redimensionamento dinâmico e cache.
- Extensível por meio de ações e filtros do WordPress.

Documentação: https://docs.alexacrm.com/wpcrm/
Usa o toolkit: [php-crm-toolkit](https://github.com/AlexaCRM/php-crm-toolkit)
Premium: https://alexacrm.com/premium/


**Integrate Dynamics 365 CRM**

https://wordpress.org/plugins/integrate-dynamics-365-crm/

- **Sincronização Bidirecional de Dados**: Sincronização de dados em tempo real entre objetos do WordPress e Dynamics 365 CRM, permitindo que alterações (criação, atualização, exclusão) sejam refletidas em ambas as plataformas.
- **Suporte para Várias Aplicações Dynamics 365**: Integração profunda com Dynamics 365 Sales, Business Central e outras aplicações do Dynamics 365, permitindo a sincronização de dados como contatos, contas, leads, pedidos, produtos e histórico de com pras.
- **Integração com Formulários**: Suporte para integração com Gravity Forms e Contact Form 7, permitindo que os dados dos formulários sejam enviados diretamente para o Dynamics 365.
- **Integração com WooCommerce**: Sincronização de dados de vendas, pedidos, inventário e histórico de compras do WooCommerce com o Dynamics 365.
- **Autenticação e Conexão**: Usa a API Web do Dynamics 365 para garantir uma integração homogênea e segura com o WordPress.
- **Documentação e Suporte**: Oferece documentação abrangente e suporte ao cliente para auxiliar na configuração e uso do plugin.

Documentação: https://plugins.miniorange.com/wordpress-dynamics-365-integration-guide
Premium: https://plugins.miniorange.com/wordpress-integration-with-dynamics-crm-365-apps#pricing-cards

**Comment by marinarcruz** [comment]
@brunosmartin ficou de fazer uma conversa sobre esse diagnóstico com Eve e Ester

**Comment by marinarcruz** [comment]
Eve testou as configurações, mas surgiram dois tipos de erros que está reportando na issue, ainda não conseguiu se conectar ao CRM do Ethos.
Precisamos definir como armazenaremos os dados referentes aos pedidos de Solicitações. Dúvida com Rafa e Bruno: Se a ação for coletar dados por formulário somente, precisaremos enviar um email.Se for por meio de um CPT, precisaremos criar um fluxo de atualização do status do pedido para ser exibido na Área de Associados.

Nos formulários de solicitações de download, como armazenar os dados para a newsletter? Eles já possuem uma lista de emails no CRM que compila esses dados. A coleta de dados permite ter dados duplicados. 

Precisaremos validar o fluxos com o Leo e com a Lívia, considerando as possibilidades do PMP. Existe uma necessidade de entender como eles fazem algumas etapas do fluxo atualmente para poder entender como integrar algumas dessas etapas no novo fluxo.
