### ISSUE TITLE
[THUMBNAIL] inserir thumbnail vazia no post card

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#51]
Layout da thumb: https://www.figma.com/design/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2420-14942&t=oOc2e6KZqXhTOQfA-0

- [ ] inserir thumbnail vazia para posts que não possuem imagens de destaque ficarem mais apresentáveis em listas de cards

atualmente, sem thumb vazia na home:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/f88e807d-1371-4c76-8c8c-9989d4b7cb14)

atualmente, na single de posts:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/9000497f-cfd0-4c86-98b0-e561d69ffd07)

**Comment by filipesouzadev** [comment]
@daphnemartinsba eu investiguei aqui no dev e no código e aparentemente já temos uma imagem placeholder, não precisei de nenhuma ação efetiva nessa issue além da investigação. estou movendo pra validação.
