### ISSUE TITLE
[WHATSAPP] ÍCONE E DIRECIONAMENTO

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#52]
- [x] Investigar qual o plugin atualmente utilizado em produção
- [x] Instalar/configurar
- [x] Implementar ícone fixo

**Comportamento:** ele deve permanecer fixo no mesmo lugar, na tela, independente do quanto role a página

Layout o ícone se encontra à direita: 

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/6c6f54d9-4f51-4d8c-bf49-5df90f7ddcdf)

**Comment by dioliviers** [comment]
Utilizado o plugin: Chaty , está sem número no momento porque não temos um, pelo que percebi parece que o plano gratuíto dele já atende nossas espectativas.

**Comment by daphnemartinsba** [comment]
blocked: aguardando atualização da versão no repo. Staging está instável
