### ISSUE TITLE
[HOME] BLOCO DE EVENTOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#53]
Layout: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=196-2&t=zrKvqoze2r0tz7i6-0&scaling=min-zoom&page-id=112%3A2

- [x] Configurar/revisar eventos para serem listados conforme layout do figma
- [x] Estilizar bloco

**Comment by daphnemartinsba** [comment]
blocked: compra do plugin events calendar

**Comment by thiagolamonte** [comment]
Após a aquisição do plugin Events Calendar PRO, foram criados eventos testes e o bloco da home foi configurado para receber mais informações sobre o evento.

**Comment by daphnemartinsba** [comment]
> Após a aquisição do plugin Events Calendar PRO, foram criados eventos testes e o bloco da home foi configurado para receber mais informações sobre o evento. A parte superior com um "filtro" que aparece no Figma não foi encontrada nas configurações do bloco.

Foi aplicado o bloco disponível na base de conhecimento do plugin: https://theeventscalendar.com/knowledgebase/configuring-the-event-list-widget/

**Comment by daphnemartinsba** [comment]
![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/673fd110-4fdf-4742-bf62-ea8e26bd19c9)



![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/5e685549-e1ae-468d-bee6-b434f060ecd5)
