### ISSUE TITLE
[CADASTRO ASSOCIADO] Avaliar se é possível customizar formulário de cadastro do PAIDMEMBERSHIP PRO 

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#54]
O cadastro deve seguir o seguinte fluxo:

1 - Cadastro do associado
2 - Criar usuário a partir do cadastro, mas com status DESATIVADO.
3 - Após pagamento e aprovação do Ethos, ATIVAR conta do associado.

Observações: 
As contas dos associados serão contas de grupo, ou seja, um plano para vários membros: https://www.paidmembershipspro.com/add-ons/group-accounts/
Todos os planos do projeto devem ser planos por APROVAÇÃO: https://www.paidmembershipspro.com/add-ons/approval-process-membership/

- [x] Avaliar se é possível customizar formulário de cadastro do PAIDMEMBERSHIP PRO 
- [x] Avaliar se é possível alterar a status  do cadastro: HABILITADO ou DESABILITADO

**Comment by daphnemartinsba** [comment]
Formulário não será feito a partir do plugin, o formulário será criado do zero

**Comment by daphnemartinsba** [comment]
Avaliar se é possível alterar a status do cadastro: HABILITADO ou DESABILITADO: o plugin precisa ser o plano pago para que tenha uma camada de aprovação
