### ISSUE TITLE
25 ANOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#56]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=202-1091&t=zAXvospGTMzV26MD-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-18444&t=zAXvospGTMzV26MD-0&scaling=min-zoom&page-id=112%3A2

**Comment by daphnemartinsba** [comment]
- Bloco de vídeos será implementado na issue #61

**Comment by filipesouzadev** [comment]
Validação :

https://ethos.hacklab.com.br/instituto-ethos-celebra-25-anos-em-evento-em-sao-paulo-com-debate-sobre-as-desigualdades/

**Comment by caio-ascava** [comment]
Ajustar Border radius da imagem destaque
