### ISSUE TITLE
[SINGLE INICIATIVAS]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#58]
Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=280-1950&t=66RMNtE95ysrmfN6-0&scaling=min-zoom&page-id=112%3A2
Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=1838-18924&t=66RMNtE95ysrmfN6-0&scaling=min-zoom&page-id=112%3A2 

- [x] Aplicar o layout desenvolvido na single posts (#13 )

Postagens (singles) estão no CPT iniciativas: https://ethos.hacklab.com.br/wp-admin/edit.php?post_type=iniciativa

**Comment by dioliviers** [comment]
:: PS : temos um problema na single onde é necessário recarregar as páginas algumas vezes para apresentar o conteúdo, como essa single tem que ter os mesmo ajustes da single padrão, em teoria ela já está refletindo as mesmas dimensões. 

OBS: não foi testado o bloco de imagem pois existe um novo procedimento a ser aplicado, onde não importamos mais todo o bloco do hacklab/blocks, apenas o bloco necessário do hacklabbloks no tema base, neste caso vou precisar de orientação porque não participei deste novo processo ainda.

**Comment by marinarcruz** [comment]
@leopiccionia entrar para apoiar no ajuste do bloco de galerias usando o que já está no hacklab blocks
