### ISSUE TITLE
[THUMBNAIL] thumbnail vazia no post card (com modificador) vertical

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#59]
- Publicações sem categoria ou marcadas como sem categoria e sem thumbnail estão com a thumb vazia padrão do post card, contudo, como o bloco post card tem um modificador para casos verticais (como publicações), ele fica com o estilo assim:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/3d2e887d-f6cb-4604-bea6-e919ea199a0d)

- [x] Adaptar imagem para ficar centralizada, igual a aplicada na thumb de posts:
https://www.figma.com/design/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=2420-14942&t=9tuCrNLctKyeae3o-0

**Comment by dioliviers** [comment]
Verificado que o problema também se reflete na home, verificando...

**Comment by dioliviers** [comment]
Ajustado card de placeholder na home e na single do CPT publicações.
