### ISSUE TITLE
[HOME] Criação/adaptação de BLOCOS e aplicação de LAYOUT

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#6]
- [x] Avaliar e adaptar os blocos 
- [x] Implementar o estilo  
- [x] Aplicar responsivo
- [x] Aplicar estilo na edição da home
  - blocos devem ser parecidos com a visualização da home para UX do cliente

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=196-2&t=JO14xBmuEvtqhu4E-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18240&t=JO14xBmuEvtqhu4E-0&scaling=min-zoom&page-id=112%3A2

**Comment by marinarcruz** [comment]
24/05: Leo estimou que finaliza dia 27/05

**Comment by caio-ascava** [comment]
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/8b696200-bfa7-4294-92d8-4c57b0f07fdf)
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/2f6580fe-908d-4879-b9fa-43aa5cfc3492)

**Comment by caio-ascava** [comment]
![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/ff42fd6b-375e-4ce6-b906-7f27a76d7185)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/f1b04250-c611-4506-abc7-b9d3405f4270)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/187a02e1-d826-48e6-b38b-461f2e7ec65b)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/36f3f041-f582-48aa-b0ec-a856269b9369)

**Comment by daphnemartinsba** [comment]
Ajustes passados para a #63
