### ISSUE TITLE
[BUSCA] listagem de EVENTOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#60]
Devida utilização do plugin events calendar, é necessário adequar a busca à busca do plugin, e adequar a busca do plugin às categorias do wordpress

- [x] Implementar listagem de eventos 
- [x] Implementar filtro por categorias

**Comment by thiagolamonte** [comment]
Ao filtrar por eventos são mostrados os eventos futuros, as categorias foram espelhadas com as tags que cada evento já trazia e assim é possível filtrar pelas abas.

**Comment by daphnemartinsba** [comment]
@thiagolamonte também aplicou as tags nas categorias, seguindo mesmo fluxo de categorização realizado em posts

**Comment by daphnemartinsba** [comment]
https://github.com/Ethos-ti/SiteEthos/assets/75261677/397e317a-947f-4e55-a62c-452a8792916c
