### ISSUE TITLE
[HOME] Ajustes gerais

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#63]
Continuação da issue #6 
- [ ] 12. Este sub-menu tambem é mais centralizado
- [x] 16. Reduzir tamanho das thumbs dos livros

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/5f880257-30b7-420e-a28e-02efe85eab05)

Mobile:

- [ ]  1. Aumentar tamanho da thumb
- [x]  17. Aumentar o tamanho do bloco e ajustar o bloco com texto
- [x] 18. Neste submenu, pelo Figma as abas estão com quebra de linhas no Figma, e em dev não estão aparecendo os ícones
- [x] 19. Aumentar a distancia entre a thumb e o submenu e aumentar o tamanho da thumb
- [x] 20. Aumentar o tamanho do bloco e ajustar o bloco com texto
- [ ] 21. Em mobile apenas, no Figma, não possui o botão "Mais Projetos"
- [x] 22. Colocar as palavras da frase em negrito, conforme figma "materiais e atividades exclusivas"
- [x] 23. Botão Conheças os planos de associação deve estar em negrito, sem quebra de linha.
- [x] 24. No layout do Figma, mobile, não há o bloco de OPINIÃO
- [x] 25. Em dev, não aparece o bloco de EVENTOS
- [x] 28. Arredondar bordas do bloco, substituir e aumentar a fonte do termo Publicações
- [x] 29. Diminuir tamanho da fonte ou aumentar o bloco com texto, de forma que fique mais preenchido. Sendo que a distancia entre o bloco de cima e a baixo, são iguais.
- [x] 30. Diminuir tamanho da fonte, padronizar tamanho das tags e incluir data (avaliar padrão)
- [x] 31. Neste bloco, arredondar bordas, inverter icones e botões, conforme Figma. Ajustar p botão "experimente a plataforma" que está com cores invertidas e sem quebra de linha no texto. Botão "saiba mais" em negrito. E não está aparecendo o título "indicadores Ethos" dentro do bloco (abaixo do ícone)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/53f424ce-4538-4ddc-bdfe-9b07c7093dc4)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/d704549d-19f4-4a83-988b-2222d9e69683)

**Comment by daphnemartinsba** [comment]
Os seguintes pontos **também** devem **ser validados**
desktop:
1.Aumentar distanciamento entre bloco e cabeçalho, conforme Figma;
 2. Padronizar tamanho das tags
 3. Ajustar tamanho da imagem destacada para 770x433
 4. Aumentar distancia entre thumbs
 5. Incluir botão "Mais notícias"
 6. Reduzir distanciamento entre thumb e tags
 7. No Figma, o botão SAIBA MAIS tem seu fundo branco e letras pretas.
 8. Os dois títulos destes blocos: "Conferência Ethos" e "Título do outro cta" devem estar em caixa alta;
 9. Reduzir, minimamente, a largura de cada um dos dois blocos.
 10. Alterar para 'PROJETOS" em caixa alta.
 11. Este bloco com texto, no Figma está de forma centralizada (com uma quebra de linha a mais)
 13. Reduzir tamanho das thumbs e aumentar o distanciamento entre elas, conforme Figma.
 14. Título "OPINIÃO" deve estar em caixa alta.
 15. Reduz ir tamanho do bloco vertical, com aumento do ícone
 17. No Figma as datas inseridas neste bloco estão em dois formatos diferentes. Avaliar qual será o padrão.
 18. Esta borda arredondada, no Figma, nesta parte inferior do bloco é mais arredondada que a superior.
 19. Ícone do Figma é diferente
 20. Diminuir line height para 35,2px
 21. Os dois botões, pelo Figma, possuem as palavras escritas em BOLD (negrito)

Mobile: 
 2. Padronizar tamanho das tags
 3. Reduzir distanciamento entre Tag e thumb
 4. Diminuir o arredondamento da borda
 5. Aumentar o tamanho do bloco de texto com os títulos, conforme Figma
 6. Incluir botão "Mais Notícias"
 7. Incluir título de AGENDA
 8. Pelo Figma, a imagem e o texto "CE conferência ethos 360° estão mais ampliados.
 9. Bordas mais arredondadas
 10. Título deve estar em caixa alta
 11. Aumentar tamanho da fonte
 12. Inverter cores, com fundo branco e letras pretas
 13. Título deve estar em caixa alta
 14. Diminuir tamanho de fonte
 15. Inverter cores, com fundo branco e letras pretas
 16. Diminuir distância entre blocos e padronizar a palavra "PROJETOS" em caixa alta.
 26. Tag está quebrando
 27. Padronizar tamanho da tag

**Comment by filipesouzadev** [comment]
Item 24 - Acredito não ser uma boa ideia ocultar o botão só no mobile já que ele leva para outras publicações do termo.
