### ISSUE TITLE
[SLUGS]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#72]
- [x] Alterar slug das archives:
  - Solicitação: Novidades para /notícias
  - /posicionamentos-institucionais
  - /iniciativas
  - /opiniao
  - /publicacoes

**Comment by thiagolamonte** [comment]
https://ethos.hacklab.com.br/iniciativas/
https://ethos.hacklab.com.br/publicacoes/
https://ethos.hacklab.com.br/tipo-post/noticias
https://ethos.hacklab.com.br/tipo-post/opiniao
https://ethos.hacklab.com.br/tipo-post/posicionamentos-institucionais
