### ISSUE TITLE
[Cabeçalho] Ajuste campo de busca mobile

### ISSUE THREAD

**Issue by caio-ascava** [Ethos-ti/SiteEthos#76]
- [x] campo de busca sobrepõe o ícone do menu, apenas pelo Chrome - S23

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/fd80fac1-e8f1-4b66-ab83-24120eeaf14c)

- [x] De acordo com edições anteriores, importante avaliar nesta fase final todo o comportamento do cabeçalho após o ajuste. Considerando o hamburguer e lupa, mobile, S23 (Chrome), Iphone (Safari) e Desktop

**Comment by daphnemartinsba** [comment]
S23 - chrome:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/a06b6e8b-fe7f-4d9b-80cc-d464dddc3c13)
