### ISSUE TITLE
[BUSCA] Ajustes

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#78]
- [x] Exibir texto completo no campo de busca (atenção no limite para que não extrapole o campo)

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/ac1f1604-5645-4b45-a4d7-d1100bcd3412)

- [x] dropdown: alterar "Eventos" para Próximos Eventos

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/b196b76f-75dc-4a89-a495-6bece7f47ce5)

- [x] Aplicar estilo da sombra do select no firefox

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/bbcad943-e63d-4db9-86a2-0caa83943a35)

- [x]  Retirar aba cinza nos filtros das categorias no samsung:
![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/5eb9c3ac-df37-45db-84f5-30dbbe5180c1)
- [x] select dos filtros está extrapolando tela Samsung S23

**Comment by barbaburns** [comment]
no item Retirar aba cinza nos filtros das categorias no samsung, quando se scrolla o barra cinza desaparece.
