### ISSUE TITLE
[CABEÇALHO]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#8]
Menu superior
- [x] Criar ícones para as redes sociais (componentes devem ser editáveis pelo usuário).
- [x] Criar ícones com ferramentas de acessibilidade: contraste, tamanho de letra, áudio, impressão

Menu principal
- [x] Inserir logo do Ethos
- [x] Criar Menu Principal com itens e subitens (inserir seta quando item tiver subitem)
- [x] Quando deslogado, exibir botão QUERO ME ASSOCIAR com destaque e o botão ENTRAR
- [x] Quando logado, exibir apenas o botão ÁREA DO ASSOCIADO
- [x] Inserir lupa de busca/pesquisa

desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=196-2&t=Rh94H9sA7RFzONfF-0&scaling=min-zoom&page-id=112%3A2

desktop / dropdown: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=216-11&t=qtbX0ktYB5KmqClv-0&scaling=min-zoom&page-id=2412%3A23337

mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18240&t=Rh94H9sA7RFzONfF-0&scaling=min-zoom&page-id=112%3A2

mobile / hamburguer & busca: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=948-9415&t=qtbX0ktYB5KmqClv-0&scaling=min-zoom&page-id=2412%3A23337

**Comment by barbaburns** [comment]
Quando o campo da busca abre ele empurra os itens do menu. Seria legal pensar no layout para resolver isso.
