### ISSUE TITLE
[ASSOCIAÇÃO] CADASTRO DO USUÁRIO/GRUPO e SALVAMENTO DE DADOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#81]
No momento, os dados são salvos conforme eles são preenchidos e um usuário/grupo é criado no passo 3 do formulário. Isso faz com que ao preencher o email, antes de enviar o formulário, o email fica salvo. Caso o usuário não finalize o formulário, o email permanece salvo e ele não pode tentar se associar novamente com o mesmo email

- [x] Quando o formulário for preenchido, ficar salvo por 24 horas antes de finalizá-lo. Após isso, apagar o rascunho caso não tenha finalizado.

- [x] Ao criar um cadastro na associação, o mesmo só pode acessar a área de associados após a aprovação pelo painel do WP
- [x] Ao criar um cadastro na associação e não aprová-lo, ele deve ser apagado ou pelo menos não ter acesso à área de associado

**Comment by daphnemartinsba** [comment]
blocked: depende do funcionamento do login #30

**Comment by leopiccionia** [comment]
Usuário não será mais apagado, mas enviado para o CRM (#91).

**Comment by caio-ascava** [comment]
Comecei um cadastro e parei ele antes de terminar a etapa 3 (só preenchi até a etapa 2). Após o cron, o usuário deve sumir. 
Leo disse que tem como chamar esse cron manualmente via plugins, mas segui preenchendo novamente os dados e:

- [ ] Ao realizar um  cadastro de novo usuário, após o preenchimento da etapa 3, independente do plano selecionado aparece um erro crítico.

![Image](https://github.com/user-attachments/assets/adba1d7b-9ff8-45cf-8917-0ca5e38e998a)

**Comment by marinarcruz** [comment]
relacionada com a issue 91, que precisa que os dados sejam salvos logo no primeiro formulário.

**Comment by daphnemartinsba** [comment]
Erro não foi reproduzido, fluxo está funcionando no momento
