### ISSUE TITLE
[FORMULÁRIO DE ASSOCIAÇÃO] Calcular VALOR SUGERIDO

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#82]

**Comment by leopiccionia** [comment]
O valor sugerido costumava funcionar na etapa 4, mas parou de funcionar, creio eu, durante a refatoração da quinta-feira (?).

No entanto, acho que esse valor é deslocado naquela tela. Não há um jeito confiável de afirmar quanto custará uma associação (tela 4) sem saber quantos membros associados a organização terá (tela 5).

**Comment by daphnemartinsba** [comment]
Micro empresa - plano conexão:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/660a64ce-75ff-4c3a-a117-32f7c3aed21f)

Micro empresa - plano essencial:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/8e744b0d-4568-42f6-bb31-b4d3041b8967)

micro empresa - plano vivência:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/15850124-6bbd-45df-bb9e-2827a0cfeb83)

micro empresa- plano institucional:


![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/f7be7faf-5051-4492-9873-98189f5ef2c4)
