### ISSUE TITLE
[ASSOCIE-SE] Ajustes no bloco de vídeo e nas tabelas

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#85]
- [x] Ajustar tabela de contribuição associativa:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/2892bbad-4108-4e1f-b20a-ffae6421afcb)

- [x]  Ajustar imagens da tabela: 

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/af4defe8-a2db-489a-8b66-e49aa2b72567)

- [x] Ajustar bloco de vídeo:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/48be4a7a-29d7-4385-8505-b4c843fed11c)

Layout figma: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=4170-26344&t=J6Q08iEJBlzpXPXF-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2

**Comment by dioliviers** [comment]
@daphnemartinsba falta o cliente enviar os logos para fazer o slider no final da página, provavelmente vamos ter que solicitar para o cliente conforme informações do @mlordep

**Comment by daphnemartinsba** [comment]
- serão inseridas logos genéricas que serão alteradas conforme forem fornecidas (foram solicitadas)
