### ISSUE TITLE
[RODAPÉ]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#9]
- [x]  Inserir logo do Ethos
- [x] Inserir ícones para as redes sociais (componentes devem ser editáveis pelo usuário).
- [x] Inserir informações de contato do instituto.
- [x] Criar menu/widget do rodapé.

rodapé desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=196-2&t=Rh94H9sA7RFzONfF-0&scaling=min-zoom&page-id=112%3A2

rodapé mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18240&t=Rh94H9sA7RFzONfF-0&scaling=min-zoom&page-id=112%3A2

**Comment by caio-ascava** [comment]
os ícones das redes sociais estão inseridos via código e precisam ser alterados conforme Figma. Bruno comentou que esta alteração no cabeçalho será realizada futuramente, pois os ícones serão alterados.

os ícones de redes socias não é pelo iconefy pq o Burns adequou conforme tema base e para mexer nos ícones ele irá avaliar se criarão novos modelos.. O Leo comentou que hj a imagem é alterada via código (tanto cabeçaho quanto rodapé), mas que ainda estão avaliando se será por imagens ou por ícone .... mas que o ajuste de ícones da redes sociais será uma tratativa posterior ainda não definida
