### ISSUE TITLE
[FORMULÁRIO DE ASSOCIADOS] Campo de SENHA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#90]
- [ ] Inserir campo de senha na segunda etapa do formulário, nos dados do responsável
layout: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=4170-28749&t=7aPNF3UVTVnhbm5P-0&scaling=min-zoom&content-scaling=fixed&page-id=112%3A2

**Comment by leopiccionia** [comment]
Commit https://github.com/Ethos-ti/SiteEthos/commit/6b3677063dfb0750d5770ee8dfae353e1c43debf deve ter corrigido o problema.
