### ISSUE TITLE
[DESIGN] Revisão dos Design/Brand Tokens

### ISSUE THREAD

**Issue by marinarcruz** [Ethos-ti/SiteEthos#92]
- [x] Definição de padrão da fonte para h1, h2, h3, h4, h5, e h6 no tema base e no ethos

Precisa definir como será feito, no momento, no ethos, está despadronizado.

- [x] Aplicar padrão no design tokens

**Comment by daphnemartinsba** [comment]
- Brand tokens atualizados: https://www.figma.com/design/HJanIoNJS8SynxptNSqcji/Ethos-UI?node-id=6512-16737&t=X4RZxsMD0v4aQiK8-0

**Comment by daphnemartinsba** [comment]
typograph foi atualizado com especificações do brand tokens para os títulos. Títulos de posts e páginas seguem determinações de post content
