### ISSUE TITLE
[RECUPERAÇÃO DE SENHA] RECAPTCHA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#96]
Devido ao uso do paid membership pro, a exibição do recaptcha na página de recuperação de senha necessita de investigação

- [x] Aplicar e exibir recaptcha na página de recuperação de senha

**Comment by dioliviers** [comment]
criado pull Request: https://github.com/strangerstudios/paid-memberships-pro/pull/3073 aguardando aceitar o pull request.

**Comment by caio-ascava** [comment]
Ate o momento o recaptcha não aparece na página.
![Image](https://github.com/user-attachments/assets/962a8856-c691-4502-92cf-576b09b3c7b9)

**Comment by dioliviers** [comment]
Bom dia, conforme já dito foi criado um Pull Request e assim que a equipe do plugin do paid member aceitar o reCaptcha irá aparecer, segue abaixo novamente o link da PR 

https://github.com/strangerstudios/paid-memberships-pro/pull/3073

vou deixar como blocked e deixar em to do até a PR ser aprovada

**Comment by dioliviers** [comment]
Existe um diálogo com um dos representantes do plugin, segue abaixo para acompanhamento: 
https://github.com/strangerstudios/paid-memberships-pro/issues/3072

**Comment by marinarcruz** [comment]
podemos fazer o hook direto no código mas, se atualizarem o PMPro, perderemos essa configuração.

**Comment by dioliviers** [comment]
a PR foi fechada pois os desenvolvedores abriram outra com uma solução similar, assim que eles implementarem será apresentado no nosso tema. 
https://github.com/strangerstudios/paid-memberships-pro/pull/3073

**Comment by dioliviers** [comment]
Já foi feito o merge, provavelmente já virá na próxima atualização : https://github.com/strangerstudios/paid-memberships-pro/pull/3090

**Comment by marinarcruz** [comment]
bloqueada: precisa do Leo para entender como aplicar o hook no plugin de captcha, conforme foi feita a última atualização.
