### ISSUE TITLE
[SUSTENTAÇÃO/INFRA] CRIAR DEV e CONFIGURAR/ATUALIZAR PLUGINS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#97]
- [x] Criar dev
- [x] Criar staging no azure novo.ethos

- Ambiente atual ficará de histórico

### Plugins 
Verificar se estão instalados e atualizamos, caso não, instalar e atualizar: **caso não sejam plugins padrões, avisar**
- [ ] W3 Total cache: Instalar, configurar e testar

- [ ]  Cloudflare Page Cache: Instalar, configurar e testar

- [x]  Wordfence: Instalar, configurar e testar

- [x]  Verificar se já tem/Configurar envio de email: utilizar mailgun

- [x]  Verificar memória disponível para o site: Instalar o plugin wp memory usage e ver no painel qual a memória disponível e garantir memória wp 256M e PHP 512

- [ ] Instalar Yoast SEO

**Comment by marinarcruz** [comment]
Importante saber que na Azure não é possível fazer a atualização dos plugins via painel. É preciso fazer processo de dockerização.

**Comment by marina-hacklab** [comment]
WP Memory Usage instalado. Limites de memória disponíveis: WP 128MB, WP-Admin 256MB, PHP 512MB
![image](https://github.com/user-attachments/assets/d05e96ae-59e6-4760-b7ef-77a69dd0952c)

**Comment by marina-hacklab** [comment]
Mailgun testado e funcionando. Teste via e-mail de redefinição de senha:
![image](https://github.com/user-attachments/assets/efcf1162-945a-409e-8ab5-764b04fe9b19)

**Comment by marina-hacklab** [comment]
Problemas encontrados:

- W3 Total Cache: quando ativado o plugin piorou visivelmente o desempenho do site. Necessário apoio da infra e se debruçar sobre o problema.

- Cloudflare: não é possível usar nenhum dos plugins de cache do Cloudflare pois nesse site o serviço não é utilizado, e sim o Cloudfront.

- Wordfence: pôde ser instalado e configurado, porém não é possível concluir a otimização do firewall. Parece ser consequência do mesmo problema que não permite instalar plugins pelo painel do WP.
