### ISSUE TITLE
[INTEGRAÇÃO CRM] IMPORTAÇÃO DOS CADASTROS DE USUÁRIOS E EMPRESA

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#98]
- [x] Importação inicial dos dados do usuários e empresas: CRM -> WP
  - [ ] definir fluxo inicial de acesso

**Comment by daphnemartinsba** [comment]
- Fazer pelo wp-cli: import all

**Comment by leopiccionia** [comment]
Falta só a importação de imagens.

**Comment by daphnemartinsba** [comment]
- Cadastro de grupos econômicos estão funcionando: testado com o acesso do contato principal do grupo econômico GREEN4T englobando a empresa GREEN4T SOLUÇÕES TI SA 
-

**Comment by daphnemartinsba** [comment]
sera resolvida na #132
